### PR TITLE
Update coldstart.jittrace file

### PR DESCRIPTION
**Pull request by safihamid**
This is to fix the recent cold start regression.

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [X] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [X] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [X] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by pragnagopa — DISMISSED** [review]
PR only has coldstart.jittrace update. So did the test did not catch the regression?

**Comment by safihamid** [comment]
@pragnagopa looks like it didn't because in order to make sure the test is not super noisy we accepted a 1% failure to be ok. Also, the test looks at the signature of past methods to detect new failures so if there are several new methods added without a change to signature of old methods the test will not be able to detect them. I sent an email about this

**Comment by pragnagopa** [comment]
Thanks for the details @safihamid ! Approved PR.

**Review by paulbatum — DISMISSED** [review]

**Review by pragnagopa — APPROVED** [review]

**Pull request merged**
