### PR TITLE
Add LanguageWorkerConfigurationService

### LINKED ISSUE #4574: Refresh language worker options after specialization
WorkerConfigs are initialized here:
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/Configuration/LanguageWorkerOptionsSetup.cs#L25

Worker configs need to refreshed after specialization to allow customizing any language worker processes that start inside jobhost

cc @christopheranderson

### PR DESCRIPTION
**Pull request by pragnagopa**
- Replaced LanguageWorkerOptionsSetup with LanguageWorkerConfigurationService
- Reloading language worker config only during specialization

Issue:
- Using LanguageWorkerOptionsSetup forces adding LanguageWorkerOptionsSetup at WebHost level and JobHost level as JobHost cannot rely on webhost configuration setup.

- This forces, parsing language worker config on every jobhost restart even though these options cannot be modified

Alternative approach considered:
- Adding application level language worker options similar to `ScriptApplicationHostOptions` will introduce application dependency on language worker options.

Fixes #4574

### CODE REVIEW

**Comment by fabiocav** [comment]
Flowing the configuration into the JobHost scope is feasible and would be preferable

**Comment by pragnagopa** [comment]
cc @soninaren @yojagad 
Reopening this PR as this change is needed to avoid reading worker.config.json files at the jobhost level.
Language worker configs are cached at webhost level and services at JobHost level need access to them similar to FunctionMetdataProvider.

@fabiocav - Flowing worker config as configuration does not look like the right approach as parsing worker config files is a one time operation and cannot be changed after application starts.

**Comment by pragnagopa** [comment]
This PR is stale. Need to rebase. Will update the PR after discussing options to address this issue with @fabiocav

**Comment by pragnagopa** [comment]
Assigning to @soninaren for follow up

**Comment by fabiocav** [comment]
Closing stale PR. Please reopen if still relevant.

**Pull request closed without merging**
