### PR TITLE
updating perf runs to handle v3

### PR DESCRIPTION
**Pull request by brettsam**
@alrod -- I've deployed this to the perf dashboard site already and I think it's running okay. The v3 builds aren't working correctly which I'm still working on.

### CODE REVIEW

**Comment by brettsam** [comment]
@alrod does this look okay to you? We're getting reports for both v2 and v3 now so it's working but I can rearrange the approach if you'd like me to.

**Comment by alrod** [comment]
Are you using same app for V3 ()? You did not create new one?

**Comment by fabiocav** [comment]
@brettsam, are you planning on merging this?

**Comment by brettsam** [comment]
whoops, thought i had!

**Comment by brettsam** [comment]
And correct, @alrod, I'm using the same app, just deploying a v3 site extension.

**Pull request merged**
