### PR TITLE
Add compile errors to the functionerror collection (#8518)

### PR DESCRIPTION
**Pull request by chiangvincent**
This PR cherry picks the already merged PR for dev into the v3.x branch -- see [PR link](https://github.com/Azure/azure-functions-host/pull/8518)

Co-authored-by: Vincent Chiang <vchiang@microsoft.com>

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]

**Comment by pragnagopa** [comment]
@chiangvincent - please take a look at the test failures

**Comment by jviau** [comment]
~Is this not already checked in? #8518~ 

Never mind, this is a different target branch.

**Review by jviau — APPROVED** [review]

**Pull request merged**
