### PR TITLE
4.2.1 Hotfix - Change Java Worker Version Number

### PR DESCRIPTION
**Pull request by VpOfEngineering**
Regressing Java worker version to 2.1.0-SNAPSHOT to fix  2.2.0-SNAPSHOT bug.
https://github.com/Azure/azure-functions-java-worker/releases/tag/2.1.0-SNAPSHOT

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by kaibocai — APPROVED** [review]
LGTM

**Review by shreyas-gopalakrishna — APPROVED** [review]

**Review by amamounelsayed — APPROVED** [review]

**Comment by pragnagopa** [comment]
Please send PR to dev branch only. We need to cherry pick from dev to release branches. Also, please update description with the link to Java worker releaase notes that has details on regression. Updating the target branch to dev

**Comment by amamounelsayed** [comment]
> Please send PR to dev branch only. We need to cherry pick from dev to release branches. Also, please update description with the link to Java worker releaase notes that has details on regression. Updating the target branch to dev

We updated the description, this is the cherrypick for the merge to dev https://github.com/Azure/azure-functions-host/pull/8191

**Comment by pragnagopa** [comment]
@VpOfEngineering - target branch  does not look right - please force push to release/4.x-hotfix branch from prev release tag

**Comment by amamounelsayed** [comment]
> @VpOfEngineering - target branch does not look right - please force push to release/4.x-hotfix branch from prev release tag

Thank you so much, to clarify this release is still UD0, should we still treat as hotfix branch?

**Pull request closed without merging**
