### PR TITLE
Developer/wangbill/4.9.0 hotfix

### PR DESCRIPTION
**Pull request by YunchuWang**
ORIGINAL PR: https://github.com/Azure/azure-functions-host/pull/8582
COMMIT ID: 4b38a373845e34c0a0a3356b84c10b3d7c36374e

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by gavin-aguiar — APPROVED** [review]

**Review by VpOfEngineering — CHANGES_REQUESTED** [review]
Two requests
1. Can this be created with cherry-picking the merge commit from the dev PR? To preserve commit history?
2. Why was the patch version reset to 4.9.0? Wasn't your original commit correct - we are cutting this as 4.9.1?

**Comment by YunchuWang** [comment]
1. This is cherry picked from dev with merge conflict 
2. I was referring to hotfix guide, as discussed will revert.
> Two requests
> 
> 1. Can this be created with cherry-picking the merge commit from the dev PR? To preserve commit history?
> 2. Why was the patch version reset to 4.9.0? Wasn't your original commit correct - we are cutting this as 4.9.1?

**Review by VpOfEngineering — CHANGES_REQUESTED** [review]
`This is cherry picked from dev with merge conflict`

It will help us avoid merge conflicts in the future if we can resolve these conflicts. Please let me know what the conflict is, and I can try and help.

**Comment by YunchuWang** [comment]
> `This is cherry picked from dev with merge conflict`
> 
> It will help us avoid merge conflicts in the future if we can resolve these conflicts. Please let me know what the conflict is, and I can try and help.

yes the merge conflict is in release_notes.md, it is resolved 
image

**Review by VpOfEngineering — APPROVED** [review]
LGTM

**Pull request merged**
