### PR TITLE
Removed unused param from LinuxAppServiceEventGenerator.

### PR DESCRIPTION
**Pull request by kashimiz**
### Issue describing the changes in this PR

Small fix related to #6887

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by pragnagopa — DISMISSED** [review]

**Comment by pragnagopa** [comment]
@kashimiz - there are build failures. Can you please follow up?

**Comment by divyagandhisethi** [comment]
> 
> 
> @kashimiz - there are build failures. Can you please follow up?

yes I assume you need to update the caller as well?

**Review by divyagandhisethi — DISMISSED** [review]
Can you please update the caller to remove IEnvironment.

**Comment by pragnagopa** [comment]
@kashimiz  - Can you please follow up and update the PR fixing the build errors? Thanks!

**Review by pragnagopa — APPROVED** [review]

**Comment by pragnagopa** [comment]
@divyagandhisethi - build errors are fixed ! Will be merging the PR soon (dismissing review fyi :))

**Pull request merged**
