### PR TITLE
Update Node.js Worker to 2.1.0

### LINKED ISSUE #344: Add support for ES Modules
Allow Node 14 functions to use ESM by supporting `.mjs` files.

A function would look something like this: 

```js
// index.mjs
export default async function (context, req) {
    context.res = {
        body: process.version
    };
};
```

### PR DESCRIPTION
**Pull request by mhoeger**
Change also to support index.mjs in the simplest way possible. This is being done to make sure ES Modules make it into this next deployment, while saving the engineering improvement to do this the right, extensible way for a later item this sprint: https://github.com/Azure/azure-functions-host/issues/6955 . **Will remove hard-coding soon!**

Node.js Worker 2.1.0: https://github.com/Azure/azure-functions-nodejs-worker/releases/tag/v2.1.0

### Issue describing the changes in this PR

resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/344

### Pull request checklist

* [X] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [X] Otherwise: I've added my notes to `release_notes.md`
* [X] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [X] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by pragnagopa** [comment]
Please add link to node js worker release notes in the PR description

**Comment by pragnagopa** [comment]
Can you please check if  the changes in the PR can be handled in nodejs worker i.e if script file is empty or not set in function load request - > default to `index.js` or `index.mjs`

**Comment by mhoeger** [comment]
@pragnagopa - Tested and if script file is empty, this change works to find `index.mjs` (or `index.js`)! The case of a script file not being set in function load request doesn't happen because of the validation here: 
https://github.com/Azure/azure-functions-host/blob/c198263bdcf7539c0765fdea6a8ec82b93c90a70/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L167-L173

**Comment by pragnagopa** [comment]
Thanks @mhoeger  for the the follow up.
So the check you pointed out can be removed : https://github.com/Azure/azure-functions-host/blob/c198263bdcf7539c0765fdea6a8ec82b93c90a70/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L167-L173  if NodeJs worker adds this check as part of function load response? - Will you be handling this as part of the follow up issue #6955 ?

**Review by pragnagopa — APPROVED** [review]

**Comment by mhoeger** [comment]
@pragnagopa - I think we'll need that check still since it's relevant for C# :\ What I was thinking of doing was changing that check from being hard-coded to a value from the worker config. But yes was planning on exploring solutions in #6955 !

**Pull request merged**
