### PR TITLE
[Pack] Remove HttpRequestMessageFeature

### LINKED ISSUE #5763: [HttpWorker]Investigate 500s in daily perf runs
Few requests for HttpWorker test:
https://functionsperfst.blob.core.windows.net/dashboard/2020-03-09%2014_22_58/index.html

are failing with 500s. Need to investigate.

### PR DESCRIPTION
**Pull request by yojagad**
Fixes #5763 and #5085

### CODE REVIEW

**Comment by pragnagopa** [comment]
cc @anthonychu , @jeffhollan  - This PR fixes 500s we are seeing in perf runs.

This is great. Thanks @yojagad. Looking forward to green perf runs!

**Review by pragnagopa — APPROVED** [review]

**Comment by pragnagopa** [comment]
Please do check if we can remove nuget reference: microsoft.aspnetcore.mvc.webapicompatshim

**Comment by yojagad** [comment]
> Please do check if we can remove nuget reference: microsoft.aspnetcore.mvc.webapicompatshim

Tried that but it looks like HttpBinding still needs this (for HttpResponseMessageOutputFormatter)
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Binding/Http/HttpBinding.cs#L210

**Pull request merged**
