### PR TITLE
[pack] Updating build to check for vulerabilties

### LINKED ISSUE #9272: Update host builds to check and flag vulnerabilities in the resolved dependencies.

### PR DESCRIPTION
**Pull request by soninaren**
### Issue describing the changes in this PR

resolves #9272 

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by jviau** [comment]
@soninaren this is built into NuGet targets: https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1901-nu1904

Maybe we just need to upgrade our dotnet sdk in the build? Should consider adding a `global.json` as well

**Review by jviau — APPROVED** [review]
This is fine for now. Can you add comments to the changes to remove them when we update to .net8 SDK? And instead rely on the built in vulnerability checks.

**Comment by soninaren** [comment]
> This is fine for now. Can you add comments to the changes to remove them when we update to .net8 SDK? And instead rely on the built in vulnerability checks.

sure

**Review by satvu — APPROVED** [review]

**Pull request merged**
