### PR TITLE
[pack] Updated Webjobs SDKs

### PR DESCRIPTION
**Pull request by azfuncgh**

### CODE REVIEW

**Comment by yojagad** [comment]
@fabiocav Just checking.. Is there something else that needs to be done here ?

**Comment by mathewc** [comment]
@yojagad @fabiocav I had proposed that we take a new version of the SDK + AI logger packages, since the version we're taking here have a bug which is addressed by https://github.com/Azure/azure-webjobs-sdk/pull/2674.

**Comment by yojagad** [comment]
If someone can publish a new version of webjobs sdk, other packages, I can update this PR with the same and then we can go from there?

**Comment by mathewc** [comment]
New packages published. You're good to go with this PR now.

**Comment by yojagad** [comment]
Thanks @fabiocav !!

**Review by yojagad — APPROVED** [review]

**Review by fabiocav — APPROVED** [review]

**Pull request merged**
