### PR TITLE
Include minimum durable payload to sync trigger

### LINKED ISSUE #7394: Refactor the SyncTrigger extensions payload to make it generic
#### What problem would the feature you're requesting solve? Please describe.
Currently as a tactical solution for LIMA scenarios, FunctionsSyncManager is adding the extensions portion of host.json to the sync triggers payload only for Kubernetes environments. We want to remove that restriction so it's applied in other environments as well, which will allow us to address https://github.com/Azure/azure-functions-host/issues/5390 in a general manner.

For more details see the discussion in : https://github.com/Azure/azure-functions-host/pull/7386

CC: @pragnagopa @mathewc @cgillum 

#### Describe the solution you'd like
Make the `extensions` payload to generic so it's always returned, not based on sku/environment. We'll need to update the minimal response that is returned when the full payload `{ triggers: [], functions: [], extensions: {}, secrets: {} }` is over the size limit. The new minimal format will be `{ triggers: [], extensions: {} }`. This way, consumers can rely on host level extensions config in addition to the functions config already included in the triggers data.

#### Describe alternatives you've considered
We can keep it only available for Kubernetes Environment, However, Container usage for the AppService will be the same. 

#### Additional context
We considered the PR https://github.com/Azure/azure-functions-host/pull/7386 as hot fix. We need to refactor and add proper test for the generic usage.

### PR DESCRIPTION
**Pull request by TsuyoshiUshio**
Replace https://github.com/Azure/azure-functions-host/pull/8188 

This PR add SyncTriggerPayload for Durable Functions.  `triggers` section will be following.  The payload only includes the following sections of the `host.json` payload.  It doesn't include AppSettings and Default Value. If the section exists, it will included in the payload.  For more behavior, refer to the Integration testing Payload section.   

* `hubName`
* `storageProvider`  Durable Functions V2 only
* `maxConcurrentActivityFunctions` Durable Functions V2 only
* `maxConcurrentOrchestratorFunctions` Durable Functiosn V2 only

```json
[
  {
    "authLevel": "anonymous",
    "type": "httpTrigger",
    "direction": "in",
    "name": "req",
    "functionName": "function1"
  },
  {
    "name": "myQueueItem",
    "type": "orchestrationTrigger",
    "direction": "in",
    "queueName": "myqueue-items",
    "connection": "SQLDB_Connection",
    "functionName": "function2",
    "taskHubName": "DurableTask",
    "storageProvider": {
      "type": "mssql",
      "connectionStringName": "SQLDB_Connection",
      "taskEventLockTimeout": "00:02:00",
      "createDatabaseIfNotExists": true
    },
    "maxConcurrentOrchestratorFunctions": 10,
    "maxConcurrentActivityFunctions": 12
  },
  {
    "name": "myQueueItem",
    "type": "activityTrigger",
    "direction": "in",
    "queueName": "myqueue-items",
    "connection": "SQLDB_Connection",
    "functionName": "function3",
    "taskHubName": "DurableTask",
    "storageProvider": {
      "type": "mssql",
      "connectionStringName": "SQLDB_Connection",
      "taskEventLockTimeout": "00:02:00",
      "createDatabaseIfNotExists": true
    },
    "maxConcurrentOrchestratorFunctions": 10,
    "maxConcurrentActivityFunctions": 12
  }
]
```

### Issue describing the changes in this PR

resolves https://github.com/Azure/azure-functions-host/issues/7394

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [x] Otherwise: Backport tracked by issue/PR [#8292 ](https://github.com/Azure/azure-functions-host/pull/8292)
* [x] I have added all required tests (Unit tests, E2E tests)

CC: @cgillum @bachuv @pragnagopa

### CODE REVIEW

**Review by liliankasem — APPROVED** [review]
@fabiocav ?

**Comment by pragnagopa** [comment]
@TsuyoshiUshio  - please rebase and update the PR.

@cgillum  / @mathewc  - please review Thanks!

**Comment by cgillum** [comment]
@bachuv did you get a chance to verify this?

**Comment by bachuv** [comment]
@cgillum I'm still verifying reading the `storageProvider` host.json contents in the scale controller. I'll approve the PR once I finish testing it.

**Comment by bachuv** [comment]
Update: I modified how the scale controller was reading the `storageProvider` host.json contents from using a `JToken` to `IDictionary<string, object>` and this fixed the issue. @cgillum thanks for the help! 

Now that it's fixed, I'll make the relevant scale controller changes to use the `storageProvider` json tomorrow and update this discussion.

> @TsuyoshiUshio I don't think we can use `JToken` to store the `storageProvider` host.json contents. I see the following error when reading the trigger data in the scale controller. 
> 
> > Failed to deserialize trigger data.
> > System.Runtime.Serialization.InvalidDataContractException: Type 'Newtonsoft.Json.Linq.JToken' is a recursive collection data contract which is not supported. Consider modifying the definition of collection 'Newtonsoft.Json.Linq.JToken' to remove references to itself.
> 
> It looks like the deserialization is happening with `DataContractJsonSerializer.ReadObject()` which doesn't support `JToken`.

**Review by bachuv — APPROVED** [review]
Thanks for making these changes! I was able to confirm that the scale controller can get the relevant host.json settings.

**Comment by pragnagopa** [comment]
Thanks all for the follow up! @TsuyoshiUshio / @bachuv  is the change needed for v3?

**Comment by bachuv** [comment]
@pragnagopa - yes, @TsuyoshiUshio opened and merged PR #8292 for v3.

**Review by bachuv — APPROVED** [review]

**Pull request merged**
