### PR TITLE
Single instance of worker configs

### PR DESCRIPTION
**Pull request by mhoeger**
Fixing the worker config comparison so that it doesn't check against new instances.

This bug materialized as many language worker processes being spun up (one per function)

### CODE REVIEW

**Comment by fabiocav** [comment]
As discussed, it would be good to update the API to be clear that it returns a materialized collection.

**Comment by pragnagopa** [comment]
Thanks for the fixing this @mhoeger !

**Comment by mhoeger** [comment]
Gotta give most of the credit to @fabiocav for this :)

**Comment by pragnagopa** [comment]
This is very likely the cause of https://github.com/Azure/azure-functions-host/issues/3327

**Pull request merged**
