### PR TITLE
Update Easy Auth middleware to emit logs for internal telemetry

### PR DESCRIPTION
**Pull request by ConnorMcMahon**
Utilize the new package of Microsoft.Azure.AppService.Middleware.Functions that can emit telemetry in a way that our Linux consumption architecture can properly consume.

### CODE REVIEW

**Comment by ConnorMcMahon** [comment]
Sample log:

MS_EASY_AUTH_EVENTS 4,"RequestCompleted","","localhost:21330","/","302","0","login.microsoftonline.com",,,,,,,,"Microsoft-Azure-AppService-Middleware",,,,"-1"

**Comment by ConnorMcMahon** [comment]
Rough schema below:

MS_EASY_AUTH_EVENTS (Level),(TaskName),(SiteName),(Hostname),(Path),(StatusCode),(SubStatusCode),(RediretHostname),(Issuer),(ClientId),(Authenticated),"(AuthenticationMethods)",(UserDomain),(UserHash),"(Details)",(ProviderName),"(Message)",(SettingName),"(SettingValue)",(ContainerVersion)

**Comment by divyagandhisethi** [comment]
> 
> 
> Rough schema below:
> 
> MS_EASY_AUTH_EVENTS (Level),(TaskName),(SiteName),(Hostname),(Path),(StatusCode),(SubStatusCode),(RediretHostname),(Issuer),(ClientId),(Authenticated),"(AuthenticationMethods)",(UserDomain),(UserHash),"(Details)",(ProviderName),"(Message)",(SettingName),"(SettingValue)",(ContainerVersion)

Thank you for doing this Connor. What is container version here? Is it the host runtime version?

**Comment by ConnorMcMahon** [comment]
@divyagandhii, that's a good point. At this point it is actually no longer any different than the existing column ModuleRuntimeVersion, so that should be the column it maps to, not ContainerVersion.

**Review by balag0 — APPROVED** [review]

**Comment by balag0** [comment]
please wait till @divyagandhii also has a chance to sign off before merging.

**Comment by fabiocav** [comment]
Closing stale PRs. Please reopen if still relevant.

**Pull request closed without merging**
