### PR TITLE
[Hotfix] Update project dependencies to latest

### PR DESCRIPTION
**Pull request by v-imohammad**
### Pull request checklist

**IMPORTANT**: Currently, changes must be backported to the `in-proc` branch to be included in Core Tools and non-Flex deployments.

* [x] Backporting to the `in-proc` branch is not required
    * Otherwise: Link to backporting PR
* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by jviau — APPROVED** [review]

**Comment by Francisco-Gamino** [comment]
@v-imohammad  - Please add an entry for the release notes. You can use the following:
`Update project dependencies to the latest versions.`

Otherwise, LTGM. Thank you.

**Review by Francisco-Gamino — APPROVED** [review]
After adding the entry in the release notes, we should be good to go.

**Comment by Francisco-Gamino** [comment]
Please change the PR title to: `[Hotfix] Update project dependencies to latest`. After this, we are good to merge the PR.

**Review by fabiocav — CHANGES_REQUESTED** [review]
We should consider adding this to a hotfix branch instead.

**Comment by fabiocav** [comment]
Can you please make sure this is targeting a more specific branch (e.g., `release/in-proc-hotfix-4.x36.<actualpatch>` this should eventually be replaced by a tag only, but in the meantime, having the branch will avoid problems with the release flow.

**Comment by Francisco-Gamino** [comment]
@fabiocav - We have updated the PR. Could you please take a look? Thank you.

**Review by fabiocav — APPROVED** [review]

**Pull request merged**
