### PR TITLE
[pack]Load all workerConfigs in Placeholder Mode

### LINKED ISSUE #5420: Function language not always set in metadata when indexed
Edited description after input from Fabio:
[LanguageWorkerOptions](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/Configuration/LanguageWorkerOptionsSetup.cs) appear to not always be the correct value for the JobHost instance. 

In one case, we saw a node placeholder app (which only reads node configs) specialized to a powershell function app (which requires a powershell config) fail to initialized with a null ref. Likely, the invalidation / change token isn't being used correctly to ensure correct ordering before reading the latest LanguageWorkerOptions.

This race condition manifests as a null ref when validating a functions. The null value comes from this code to [ParseLanguage](https://github.com/Azure/azure-functions-host/blob/7c6ae82f215282c3d936cf9bb21b897d971933a0/src/WebJobs.Script/Host/FunctionMetadataProvider.cs#L165-L189) of the function. This code also needs revisiting to guard against future null refs.

Exception example:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Script.Utility.<>c__DisplayClass44_0.<ContainsFunctionWithWorkerRuntime>b__1(FunctionMetadata f) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 595
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at Microsoft.Azure.WebJobs.Script.Utility.ContainsFunctionWithWorkerRuntime(IEnumerable`1 functions,String workerRuntime) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 595
   at Microsoft.Azure.WebJobs.Script.Utility.IsSingleLanguage(IEnumerable`1 functions,String workerRuntime) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 546
   at Microsoft.Azure.WebJobs.Script.Utility.VerifyFunctionsMatchSpecifiedLanguage(IEnumerable`1 functions,String workerRuntime,Boolean isPlaceholderMode,Boolean isHttpWorker) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 518
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.GetFunctionDescriptorsAsync(IEnumerable`1 functions,IEnumerable`1 descriptorProviders) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 668
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFunctionDescriptorsAsync(IEnumerable`1 functionMetadata) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 488
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 288
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 244
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 235
```

cc: @fabiocav

### PR DESCRIPTION
**Pull request by pragnagopa**
Fixes #5420 
Verified with and without placeholder mode locally.

Verified on private stamp.

### CODE REVIEW

**Comment by mhoeger** [comment]
Thanks! Is https://github.com/Azure/azure-functions-host/issues/4574 still the long-term fix? We talked about this in person but putting this down just for to be able to reference it later - we still have a race condition ex: for custom language workers that land on a placeholder site (although not a common scenario). It does seem like this race condition could easily resurface though unless we explicitly make those options web-app scoped.

I'm also wondering if we can clean up some code here that resulted in a null: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/FunctionMetadataProvider.cs#L165L189

Can we clean up the ambiguous meaning of "null" in these spots? 

Ex: can we throw an informative exception if we know we should have found a Language but it was missing [here](https://github.com/Azure/azure-functions-host/blob/a2a11fb1adc87d6068019b7c8b6a288c37274201/src/WebJobs.Script/Host/FunctionMetadataProvider.cs#L188) instead of returning null? 

And can we be more explicit about the value we want "language" to be in http worker scenarios instead of assigning it to be null? In this code too, it looks like the code is implied to be for an http worker when script file is not found, which isn't necessarily true. One example of a bug I could see happening: a user creates an http worker that has their `HttpTrigger` folder that includes both `function.json` and `sample.dat`, as most of the templates do. In this case, our logic to determine [scriptFile](https://github.com/Azure/azure-functions-host/blob/a2a11fb1adc87d6068019b7c8b6a288c37274201/src/WebJobs.Script/Host/FunctionMetadataProvider.cs#L223) _would_ actually find that there's another file in there - sample.dat - and set scriptFile to point to sample.dat. I'm not sure if this manifests in a bug, but I could see it very easily resulting in a bug.

**Comment by pragnagopa** [comment]
> we still have a race condition ex: for custom language workers that land on a placeholder site (although not a common scenario). It does seem like this race condition could easily resurface though unless we explicitly make those options web-app scoped.

Long term fix is still #4574  as this is not a race condition.  Unfortunately as language worker options are registered at jobhost and webhost scope, the value of the options differs depending on the where these options are read.


> And can we be more explicit about the value we want "language" to be in http worker scenarios instead of assigning it to be null? 

Language is completely optional from functions host point of view. Language set to in FunctionMetdata for a given function is valid. It simple means that we do not have a worker that can handle function invocations for that function.

>  our logic to determine [scriptFile](https://github.com/Azure/azure-functions-host/blob/a2a11fb1adc87d6068019b7c8b6a288c37274201/src/WebJobs.Script/Host/FunctionMetadataProvider.cs#L223) _would_ actually find that there's another file in there - sample.dat - and set scriptFile to point to sample.dat. I'm not sure if this manifests in a bug, but I could see it very easily resulting in a bug.

Good point. Please open a separate issue for this.

**Comment by pragnagopa** [comment]
Verified on private stamp by invoking powershell function that uses node placeholder

**Comment by pragnagopa** [comment]
Ping for review! This is needed for next release.

**Pull request merged**
