### PR TITLE
Adding AI assembly to runtime assemblies list

### LINKED ISSUE #5353: Injecting TelemetryConfiguration no longer works after updating from v3-Preview to v3
Following the instructions in https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3 used to work in the v3-preview but when updating to v3 + netcoreapp3.1 TelemetryConfiguration is no longer available and function blow up with:

```
Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration'
```

This commit shows the details of the upgrade attempt:

https://github.com/andreasohlund/PublicApi/commit/2783a2b1d34beaf64d5ca82f107087239879c73a

`"APPINSIGHTS_INSTRUMENTATIONKEY": "..."` is set in `local.setting.json`

Could it be the the v3 host no longer enable telemetry when running locally?

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): v3
- Function App name: PublicApiBackend
- Function name(s) (as appropriate): N/A
- Invocation ID:N/A
- Region:N/A

#### Repro steps

Provide the steps required to reproduce the problem:

1. In v3-Preview inject a `TelemetryClient` or `TelemetryConfiguration`
2. Update to v3 and see it fail when running locally

#### Expected behavior

Should inject the `TelemetryConfiguration` according to https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3

#### Actual behavior

Injection fails with

 ```
Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration'
```

#### Known workarounds

None at the stage

### LINKED ISSUE #5511: Dropped ITelemetryInitializer DI support in version 3?
We are using Azure Functions version 3.

In version 2 we could add a custom AppInsights ITelemetryInitializer to the IServiceCollection in our startup. In version 3 this ITelemetryInitializer is never called.
Did you drop support for this or is it a bug?

According to the documentation, you are NOT supposed to call AddApplicationInsightsTelemetry().
https://docs.microsoft.com/en-US/azure/azure-functions/functions-dotnet-dependency-injection#logging-services

We are relying on some different ITelemetryInitializer's in our system. How/where can I add them to the AppInsights registration in version 3?

### PR DESCRIPTION
**Pull request by fabiocav**
Resolves #5353 
Resolves #5511

### CODE REVIEW

**Comment by fabiocav** [comment]
Validated behavior.

**Comment by spzSource** [comment]
Hi @brettsam and @fabiocav 
Is it possible to find out when this change will reach end users? Product on behalf I'm asking has a bunch of services which directly use `TelemetryClient`, so the issue delays migration to v3.

**Comment by brettsam** [comment]
This will be a part of our next release (I'd tentatively say that it's worldwide within 2 weeks). However have they tried using this workaround for now? https://github.com/Azure/azure-functions-host/issues/5353#issuecomment-580812754

**Comment by galvesribeiro** [comment]
That workaround breaks other binding like the azure storage and others...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabbera** [comment]
Did you see the following comment. It looks like this PR might be incomplete and should really be expanded:

https://github.com/Azure/azure-functions-host/issues/4952#issuecomment-581639288

**Comment by jabbera** [comment]
When will this surface? I'm on Microsoft.NET.Sdk.Functions 3.0.5 and it's still giving me this error.

**Comment by sebastus** [comment]
Likewise, I'm still experiencing the issue with Microsoft.NET.Sdk.Functions 3.0.5 while running functions in Visual Studio. My target hosting environment is AKS. I added the Startup code suggested in #5353 - this has solved the problem there.

**Comment by brettsam** [comment]
The release has been delayed as we work through some deployment issues. Note that Microsoft.Net.Sdk.Functions is unrelated to the host runtime -- the Sdk is the build tasks for things like generating function.json and extensions.json, publish behavior, etc. There's no actual host runtime bits that ship via the Sdk. So when you see a bump in that version, it's due to a bug fix or new feature added to the build system.

New host bits are downloaded in the background by VS after they've been fully deployed to production.

**Comment by cannehag** [comment]
@brettsam Any update on when this is available ?

**Comment by mauve** [comment]
How do I get notified if this has been released and I can start to inject `TelemetryConfiguration` again?

**Update:** seems to work in the latest release in my csproj:

`    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />`

**Pull request merged**
