### PR TITLE
Issue #8015: Remove TraceWriter from samples/usage

### LINKED ISSUE #8015: TraceWriter: should we remove this from templates/samples/examples?
In investigating performance, part of what I was seeing was in `TraceWriter` and allocations down that path. In talking with the team people thought this may even be removed in the current version, so went hunting. Though [`TraceWriter` is obsolete](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/TraceWriter.cs#L13), it's still used in almost all of our samples, templates, and a few documentation spots. Should we replace this with `ILogger` everywhere? I'm happy to do a PR if so.

This makes me also question whether or not we should care about optimizations on `TraceWriter*` over in the WebJobs SDK ([issue here](https://github.com/Azure/azure-webjobs-sdk/pull/2794) - specifically, a lock [in `CreateLogger` here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/TraceWriter/TraceWriterBinding.cs#L52)) was affecting my load test, of a sample. Though it's deprecated, I wonder if a non-trivial number of users are still using it and it's worth pushing some optimizations for (or, do we fully remove it in vNext to force a move to `ILogger`?)

### PR DESCRIPTION
**Pull request by NickCraver**
`TraceWriter` is deprecated but remains in the testing and samples path, driving more adoption then we want probably (see #8015) - prepping a PR in case we want to execute on #8015 and remove some noise. Or, there's a reason to keep it and this commit is useless :)

This reduces the usage down to the 1 place we want to ensure `TraceWriter` vs. `ILogger` is working correctly.

### Issue describing the changes in this PR

Resolves #8015.

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by NickCraver** [comment]
Pending test run fixes in #8051

**Review by brettsam — APPROVED** [review]

**Comment by fabiocav** [comment]
Finally getting to this during triage (somehow this fell through the cracks). Are we leaving at least a test that validates that `TraceWriter` continues to work? For the rest of them,  this is a good change.

**Comment by NickCraver** [comment]
@fabiocav I'll try and pull this during the week to update to latest - pretty sure I intentionally left 1 test in to make sure that works but will double check.

**Comment by liliankasem** [comment]
> @fabiocav I'll try and pull this during the week to update to latest - pretty sure I intentionally left 1 test in to make sure that works but will double check.

Any updates on this? Would love to get this merged :)

**Comment by NickCraver** [comment]
Merged dev in to ensure latest - confirmed this is still being tested in several places to ensure compatibility (e.g. `\test\WebJobs.Script.Tests.Integration\TestScripts\CSharp\Scenarios\run.csx` and others)

**Review by liliankasem — APPROVED** [review]

**Comment by liliankasem** [comment]
@NickCraver looks like there are still some pipeline issues to fix, otherwise should be good to merge!

**Pull request closed without merging**
