### PR TITLE
Fix for impact of enabling AppInsights on functions cold startup time

### PR DESCRIPTION
**Pull request by safihamid**
More info here: https://github.com/Azure/azure-functions-host/issues/4183

### CODE REVIEW

**Comment by brettsam** [comment]
So this will start up logging to App Insights, but with an empty InstrumentationKey? I know we're attempting to do that elsewhere to combat some other placeholder behavior (see https://github.com/Azure/azure-functions-host/pull/4214/files#diff-95490b13dc991a58a25aaac440fb875b), but that's a more targeted initialization of one module.

@lmolkova -- do you know if there will be any side effects of us doing this here?

**Comment by lmolkova** [comment]
Null or empty ikey has no bad side-effects as long as it is disposed when 'real' configuration happens. Empty-ikey-config should never coexist with the real-ikey-config.

With empty ikey all auto-collectors will be turned on and active, but AppInsights will drop data before sending it. 
If there are two auto-collectors and one is configured with empty ikey and another with the valid one, just one of them will collect, i.e. data could be collected or not, depending on which auto-collector started first.

**Comment by safihamid** [comment]
Thanks @brettsam regarding this commnet: "If there are two auto-collectors and one is configured with empty ikey and another with the valid one, just one of them will collect, i.e. data could be collected or not, depending on which auto-collector started first." 

I have been testing this change and let it run for few nights, hitting functions cold start once every 30 min and didn't see any messages to be dropped. but is there anything else we should check?

**Comment by brettsam** [comment]
@safihamid -- right now I believe Service Bus is the only logging that uses auto-collector (until Http comes online soon). It shifts the "request" telemetry from being manually logged by us to being auto-collected by App Insights. It gives you some richer data on that telemetry (and correllation, where available). 

In short, App Insights registers a listener for specific .NET diagnostic events that tell it when a request (or SB message handler) starts/finishes, along with some other details about it. Only one of these listeners can be active at a time, so if one with a null key is active, that's the one that will log.

At first I thought we'd be good here -- but since we fire-and-forget the container disposal, I think that it's possible that we'd have a null ikey listener still "active" while we're servicing a trigger that's doing this auto-tracking. It'd be a race condition something like:
- We're in standby mode with HostA
- Specialization occurs. HostA is disposed (in a background task) while HostB is initialized.
- HostB is ready and handles the request (or SB message).
- HostA is fully disposed after that initial function is invoked.

@safihamid -- how far do we need to get with these services to prevent a cold-start issue? I'm wondering if we could detect we're in placeholder mode and skip the call to Initialize() in that case... so the services would be created but not register their listeners (@lmolkova -- I assume that's where the registration occurs?): https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs#L209

**Comment by safihamid** [comment]
@brettsam the initialize method is also really impacting cold start. here are the percentages without this change:
Name                                                                                                                                                                                                                                                                                                                                     	Inc %
 + microsoft.azure.webjobs.logging.applicationinsights!Microsoft.Extensions.DependencyInjection.ApplicationInsightsServiceCollectionExtensions+<>c.<AddApplicationInsights>b__1_2(System.IServiceProvider)	 19.5
  + microsoft.azure.webjobs.logging.applicationinsights!ApplicationInsightsServiceCollectionExtensions.SetupTelemetryConfiguration                                                                        	 12.3
  |+ microsoft.ai.servertelemetrychannel!ServerTelemetryChannel.Initialize                                                                                                                                	  5.9
  |+ microsoft.ai.perfcountercollector!QuickPulseTelemetryModule.Initialize                                                                                                                               	  4.6
  |+ microsoft.ai.dependencycollector!?                                                                                                                                                                   	  1.4
  |+ coreclr!ThePreStub                                                                                                                                                                                   	  0.2
  + microsoft.azure.webjobs.script.webhost!JobHostServiceProvider.GetService                                                                                                                              	  3.6
  + microsoft.applicationinsights!TelemetryConfiguration.get_Active                                                                                                                                       	  2.0
  + microsoft.extensions.options!?                                                                                                                                                                        	  0.5
  + microsoft.extensions.dependencyinjection.abstractions!ServiceProviderServiceExtensions.GetRequiredService                                                                                             	  0.4

**Pull request merged**
