### PR TITLE
Add Breaking_Changes.md file to track breaking changes from v1 => v2 across repos

### PR DESCRIPTION
**Pull request by mhoeger**
WIP 

==
**Updated Summary:**
"The goal is to have documentation covering breaking changes in a nicely digested format" (Fabio).
Right now, this is in the form of a BREAKING_CHANGES.md file in the functions-host repo, but could be in a Wiki page (or in some other form?) instead. The idea is to have a document that is a one-stop shop for all differences in user experience that is continuously updated _by the feature owner_.

### CODE REVIEW

**Comment by mhoeger** [comment]
@fabiocav no I haven't! Could you link me?
The idea was to track any runtime changes and core SDK / extensions whenever we pull in a new nuget.

**Comment by fabiocav** [comment]
This lists known issues and should track 1.0 -> 2.0 **Functions Host** breaking changes. For SDK changes, we should have that documentation in the SDK repo.

**Comment by fabiocav** [comment]
We could also update this with breaking changes documentation: 
https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-Runtime-2.0-Overview

Runtime specific breaking changes from release to release must also be in the release notes.

**Comment by fabiocav** [comment]
Not a fan of tracking SDK changes in this repo. That has been challenging and for WebJobs SDK customers, this is also not intuitive. We can call out how some of those changes impact functions, since not all WebJobs SDK breaking changes would be Functions breaking changes, but we need to keep track of the SDK/extensions breaking changes there.

For release notes, instead of an additional file that needs to be updated with breaking change commits, ideally we'd have all the information we need in the commit details (either by a commit flag or by appropriately marking associated issue with the breaking change tag).

Any reason why having issues with the details, commit link and tag wouldn't address our needs? We can get a full list of breaking changes for a given release with a link. Those are all things that should be happening already, so I'm trying to understand if we really need to add a new step to the process instead of making sure we're following what we have in place.

**Comment by fabiocav** [comment]
To clarify, if the goal is to have documentation covering breaking changes, that's one thing, and I agree that there's value in having all runtime impacting changes (documenting how they're actually manifested in the runtime) in a central location, but for release notes and keeping track of the breaking changes, that shouldn't be the source of truth. Ideally, that document should be updated with the information coming from the issues/commit history and release notes instead.

**Comment by mhoeger** [comment]
The goal is exactly what you said - a nicely digested format covering breaking changes a functions user could experience.

Maybe the correct solution is to move this to the Wiki page. I liked the idea of having the breaking changes document as file in the repo so that it's easy to check for in PR's and so that it's tied with the commit automatically, but we could also just add details to the table. Is your main concern that it's as a .md file instead of in the Wiki?

**Comment by fabiocav** [comment]
I'm questioning so we can reason through this and understand the goal, as I think it was too broad as it was originally stated.

The following is my take on this, others may have different opinions; I think it's great to have documentation on breaking changes with this format, at this level. That's essentially what some of those Wiki pages were doing (or trying to). 

I do think that, at least for now, as we have discussed moving the Wiki content to a docs branch on the repo and use GH pages, the Wiki is a better location for things like this. The dev flow should primarily be focused on proper issue linking and labeling (we could also introduce commit flags, but that's an additional process and often cumbersome)

Some of the key things:
- This file should not be what drives release notes and breaking changes tracking, but the other way around; the content there should come from querying the breaking change commits/issues for a given release
- SDK/Extension breaking changes need to be documented in their respective repos. How those changes impact Functions users would come here (there's a difference between the two).

Again, just asking questions so we can reason through this :)

**Comment by fabiocav** [comment]
> Also the wiki hasn't been updated since December, and its format is not going to really help when it comes to breaking changes between a pair of V2 releases.
Yes. That is my the format between two V2 releases is also a concern with what is proposed with the changes here. What would that look like?

With the tag, you can easily compile a full list of breaking changes between any releases.

**Comment by fabiocav** [comment]
We need to update the Wiki. But I think we'd be in a better spot if we have issues properly linked and labeled, with good descriptions. The labeling could be in the PR as well, that might make things a bit simpler.

**Comment by mhoeger** [comment]
Note on the wiki format: the [Typescript repo](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes) has a really nice organized sidebar that we should do too. We could do a "V2 Runtime" section with overview, known issues, and breaking changes, so I think that's less of a question

**Comment by paulbatum** [comment]
Its a shame we can't make wiki edits part of a PR (since its a different repo).

Maybe if we get into the habit of asking for proof of a wiki update as part of a PR, we could address the major issue (people forgetting to update the wiki).

**Comment by fabiocav** [comment]
That's one of the reasons I've been wanting to move the wiki content to a doc branch and use GH pages for it.

**Comment by dend** [comment]
Hey folks, docs.microsoft.com PM here 👋

Is there anything preventing your team to onboard to docs.microsoft.com and point people to a page that is always hosted with the rest of the Functions documentation?

**Comment by fabiocav** [comment]
@dend thanks for reaching out! There might be concerns with how quickly/easily we can update that document if it lives at docs.microsoft.com, but I do agree that it would be a good place for it. This is something that would ideally be maintained/updated by the engineering team.

/cc @tdykstra

**Comment by tdykstra** [comment]
In an email thread @dend explained how it could work:  the docs repo would have the product repo set up as a dependency and configured to pick up Markdown files from it at build time. Then you can make changes in the doc file in the product repo, and whenever the documentation repo rebuilds, it will pick up the latest changes.

We could set this up with a stub doc for you, and then you would be able to include updates to the doc in your PRs.

**Comment by mhoeger** [comment]
That sounds pretty awesome to me!! How often does the documentation repo rebuild? And how selectively can .md docs be pulled in from our product repo?

**Comment by dend** [comment]
@mhoeger the repo rebuilds at least daily. You can be as selective as you want with the files.

**Comment by paulbatum** [comment]
I agree, that sounds like a fantastic solution.

**Comment by dend** [comment]
We just synced with @SyntaxC4 @mhoeger and @tdykstra on this - they will follow-up on configuration and content architecture. From a technical standpoint, there are no blockers.

**Comment by tdykstra** [comment]
In the related email thread, it looks as though the dependent repository solution is off the table. Another solution would be:

* The docs team takes the initial breaking changes doc from this PR and converts it to an official doc in the azure-docs-pr repo.
* After that, the engineering team can update it directly by creating PRs to the docs repo.
* To remind people to update it, the same system as what was proposed for the wiki page would work.

An alternative is for the engineering team to maintain the doc as a file in this repo (as proposed in this PR), or a wiki page. Then there are at least two options for surfacing the data in the official docs:

1. At some point close to v2 GA, the docs team converts the breaking change list to an official doc. We would have to put a "content moved" banner at the top of the page that people by then would be used to visiting for breaking changes.
2. As soon as the engineering team decides on a permanent location for the breaking change doc, link to it from the official docs, like we currently [link to the Known issues wiki page](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#known-issues-in-2x).  Given the goal of consolidating all documentation onto docs, at some future date all of these instances of wiki pages that we link to will eventually need to be converted into docs, but that would be farther in the future compared to option 1.

Thoughts?

**Pull request closed without merging**
