### PR TITLE
Update profile.ps1 template for PowerShell function apps

### LINKED ISSUE #6071: Updates to profile.ps1 to improve cold start
Updates to profile.ps1 to improve in cold start:

* Invoking Disable-AzContextAutosave before Connect-AzAccount saves 2-4 seconds
* Remove unnecessary Get-Module call saves around ~2 seconds

profile template will look like this:

``` poweshell
if ($env:MSI_SECRET) {
    Disable-AzContextAutosave
    Connect-AzAccount -Identity
}
````

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
Update profile.ps1 template for PowerShell function apps
* Fixes https://github.com/Azure/azure-functions-host/issues/6071

### CODE REVIEW

**Review by AnatoliB — APPROVED** [review]
LGTM

**Comment by Francisco-Gamino** [comment]
Hi @pragnagopa -- The checks for my PR have have not completed in 24 hours. How do I restart them? Thanks.

**Comment by pragnagopa** [comment]
@Francisco-Gamino - you need to send a PR from a branch on this repo. Tests will not run for PRs from a fork.

**Comment by Francisco-Gamino** [comment]
> @Francisco-Gamino - you need to send a PR from a branch on this repo. Tests will not run for PRs from a fork.

Thanks @pragnagopa . I have created a new PR from a branch on this repo. This PR is replaced by https://github.com/Azure/azure-functions-host/pull/6327

**Pull request closed without merging**
