### PR TITLE
Add cfs.yml vars to code-mirror.yml

### PR DESCRIPTION
**Pull request by jviau**
### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

**IMPORTANT**: Currently, changes must be backported to the `in-proc` branch to be included in Core Tools and non-Flex deployments.

* [x] Backporting to the `in-proc` branch is not required
    * Otherwise: Link to backporting PR
* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Adds some variables to our code-mirror to unblock the pipeline.

### CODE REVIEW

**Comment by liliankasem** [comment]
Looks like this one is from a fork so we can't run pipelines on it, but I guess the change doesnt matter for that anywho?

**Review by liliankasem — APPROVED** [review]

**Comment by jviau** [comment]
> Looks like this one is from a fork so we can't run pipelines on it, but I guess the change doesnt matter for that anywho?

Ah woops, didn't mean to push to my fork. But yeah - this has 0 impact to our current pipelines. Question is, can I even check in without it?

**Comment by liliankasem** [comment]
> > Looks like this one is from a fork so we can't run pipelines on it, but I guess the change doesnt matter for that anywho?
> 
> Ah woops, didn't mean to push to my fork. But yeah - this has 0 impact to our current pipelines. Question is, can I even check in without it?

I don't think so, the pipeline runs are required. But Fabio can bypass and merge for you

**Review by fabiocav — APPROVED** [review]

**Pull request merged**
