### PR TITLE
[pack] fixing broken metrics

### PR DESCRIPTION
**Pull request by brettsam**
Making this against master so we can take a hotfix

### CODE REVIEW

**Comment by brettsam** [comment]
@mathewc has a new test in PR that would be able to catch this. We need to add this interface to that test. I'm also adding self-serve alerts (just to myself for now until this is fixed) that will email us if this happens again. Will send mail on the details.

I also need to come up with a proper way to override some of these services in tests. The ordering of how we register today makes it hard.

**Comment by paulbatum** [comment]
Just curious, why did the change from `TryAdd` to `Add` help here? How was `TryAdd` failing?

**Comment by brettsam** [comment]
DI registration goes in order. So you can register services with defaults, and then override them if you want. If you use `Add()`, it “wins” and overwrites any previous registration for that type. If you do `TryAdd()`, it will only add that service if no one else had registered one.

Well, at the end of the breaking checkin, I made this `TryAdd()` to write some tests (I needed it to *not* overwrite my test service registration). I stupidly never re-tried it in production after that. So instead, our no-op default `IMetricsLogger` from `ScriptHost` was running and the `TryAdd()` from `WebScriptHost` was not. Effectively doing nothing ☹

So if you register in this order:

`TryAdd<IMetricsLogger, MetricsLogger>()`
`TryAdd<IMetricsLogger, WebHostMetricsLogger>()`

… the first one wins. By making the second one `Add()`, it will win.

So… you can see I had to comment out some test validation b/c they won’t work anymore because I can’t register my test service now because that last call “wins”. We’ll need to refactor how we set those things up, but that is lower-pri than getting this fix out ASAP.

**Comment by paulbatum** [comment]
Got it, thanks!

**Comment by mathewc** [comment]
Yes, in some of my recent work I was grappling with these very issues with service registration order, Add/TryAdd, etc. The test I'm adding in https://github.com/Azure/azure-functions-host/pull/3732/files gives us a place to add explicit tests for expected services (https://github.com/Azure/azure-functions-host/pull/3732/files). That PR is currently on hold because the changes I made fixed the product but broke some of our e2e tests because they rely on heavy service replacement/mocking. We have to clean this up so tests can mock as you need to do here, without breaking the product.

**Pull request merged**
