### PR TITLE
Udpate WorkerInitRequest

### LINKED ISSUE #6440: Add Worker_Directory in WorkerInitRequest
Add Functions_Worker_Directory in WorkerInitRequest instead of env variable.

See https://github.com/Azure/azure-functions-host/pull/6428 for more details

### PR DESCRIPTION
**Pull request by pragnagopa**
### Issue describing the changes in this PR

resolves #6440 

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [x] Otherwise: Backport tracked by issue/PR #https://github.com/Azure/azure-functions-host/issues/6465
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

NOTE: TODO will update the PR after merging and releasing:  https://github.com/Azure/azure-functions-language-worker-protobuf/pull/48

### CODE REVIEW

**Review by mhoeger — DISMISSED** [review]
Very nit comment but i think "worker_directory" might be more clear since now i'm wondering if there's a difference between worker and functions worker

Otherwise, approved and happy to re-approve if you want to take that suggestion!

**Comment by amamounelsayed** [comment]
@pragnagopa We will update the worker, please do not remove the environment variable one till we update the java worker. We will keep the issue updated. 
https://github.com/Azure/azure-functions-java-worker/issues/392

**Comment by amamounelsayed** [comment]
Thank you @pragnagopa  and @mhoeger

**Comment by pragnagopa** [comment]
Updated to worker_directory Thanks!

**Comment by pragnagopa** [comment]
@amamounelsayed  -

>  please do not remove the environment variable one till we update the java worker. We will keep the issue updated.

This PR only adds new field. I will leave the environment varaibles until java worker is updated.

**Review by yojagad — APPROVED** [review]

**Pull request merged**
