### PR TITLE
Filter out headers with empty values

### PR DESCRIPTION
**Pull request by mhoeger**

### CODE REVIEW

**Comment by mhoeger** [comment]
Note - we probably don't want to filter out for everything because this behavior is only buggy for Node.js. Correct approach is through capabilities and either explicitly opting out of those or introducing a new headers property that is typed correctly.

**Comment by mathewc** [comment]
Why do we have to do this?

**Comment by mhoeger** [comment]
@mathewc - because of the way we implemented headers in our protobuf schema (as a map<string, string>) and the "map" type doesn't accept empty values for runtimes like node. Causes buffer overrun and corrupts other parts of the message :(

https://github.com/Azure/azure-functions-nodejs-worker/issues/142 and https://github.com/Azure/azure-functions-language-worker-protobuf/issues/21

**Comment by fabiocav** [comment]
@mhoeger this was originally opened against `dev`, which is now 3.0. Do you need to retarget?

**Comment by mhoeger** [comment]
@fabiocav - yes I need to! I think that I'll do this as through a capability flag too so that there's no chance of a break on languages that don't experience this bug. Closing PR and giving it a proper bug issue to track: https://github.com/Azure/azure-functions-host/issues/5975

**Pull request closed without merging**
