### PR TITLE
Worker concurrency memory check

### PR DESCRIPTION
**Pull request by alrod**
### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by VpOfEngineering** [comment]
Please hold off on merging this until we can complete the JIT Trace today - thank you. Will update here when it is complete.

**Comment by fabiocav** [comment]
@alrod can you please update the PR details, including the issue with information, description and going through the tasks?

**Review by fabiocav — CHANGES_REQUESTED** [review]
Blocking on description/details

**Comment by ghost** [comment]
This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

**Pull request closed without merging**
