### PR TITLE
Add assemblies to runtimeassemblies.json that have types added to DI

### LINKED ISSUE #4952: Assemblies with types added to DI container are not marked as runtime assemblies, making them potentially inaccessible
When `APPINSIGHTS_INSTRUMENTATIONKEY` is set, the WebJobs SDK adds AppInsights types to the dependency injection container.  However, `Microsoft.ApplicationInsights` is not listed in the function host's `runtimeassemblies.json`, so `FunctionAssemblyLoadContext` does not ensure the runtime's version is always the one that's used.

The right thing happens in the default case, but in the event that the function app is including a `function.deps.json` in its bundle (which my app is for other reasons :smile:), then `function.deps.json` takes priority and the runtime's `Microsoft.ApplicationInsights` assembly is ignored.  This effectively blocks AppInsights types from being retrieved via DI (making https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#log-custom-telemetry-in-c-functions a hard doc to follow :innocent:).

I wrote a function to look at all ServiceTypes added to the DI container that are from a non-runtime assembly, and found the following list of types:
- Assembly: Microsoft.ApplicationInsights
  - Type: Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
  - Type: Microsoft.ApplicationInsights.Extensibility.ITelemetryModule
  - Type: Microsoft.ApplicationInsights.Extensibility.IApplicationIdProvider
  - Type: Microsoft.ApplicationInsights.Channel.ITelemetryChannel
  - Type: Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
  - Type: Microsoft.ApplicationInsights.TelemetryClient
- Assembly: Microsoft.AI.PerfCounterCollector
  - Type: Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule
- Assembly: Microsoft.Azure.WebJobs.Host.Storage
  - Type: Microsoft.Azure.WebJobs.DistributedLockManagerContainerProvider

I think that the three assemblies above need to be added to `runtimeassemblies.json`, in order to unblock scenarios 

#### Investigative information

Template fields didn't apply, but I did put together a minimal function app repro here:
https://github.com/AtOMiCNebula/FunctionHostAssemblyWoes

The `BrokenConsumer` function shows the issue with `TelemetryConfiguration`.

The `DIChecker` function enumerates all service types added to the `IServiceCollection` and lists out types that are in assemblies not listed in `runtimeassemblies.json`.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create new HTTP triggered function in empty project.
2. Follow https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#log-custom-telemetry-in-c-functions to pull a `TelemetryConfiguration` from DI.
3. Update function project to include a `function.deps.json`.

#### Expected behavior

Provide a description of the expected behavior.

Function should run successfully.

#### Actual behavior

Provide a description of the actual behavior observed.

Through step 2, the function app does not have trouble acquiring a `TelemetryConfiguration` from the DI container.  After step 3, function launch fails.

#### Known workarounds

* Remove usage of `function.deps.json`.  This causes other problems though (my app relies on this file being present to successfully use `System.ServiceModel.*` packages), and so I can't leverage it.
* Craft your own `TelemetryConfiguration`.  This isn't ideal either, since I have to go build the configuration myself which can drift from whatever the runtime sets up for everything else.

### PR DESCRIPTION
**Pull request by AtOMiCNebula**
There are service types being added to the WebJobs/Functions DI container that are from assemblies not listed in `runtimeassemblies.json`.  If a function app is using a `function.deps.json`, then that produces very hard to understand failures when trying to fetch those types from the DI container.  This adds three assemblies to the list, allowing the right thing to happen.

Fixes #4952

### CODE REVIEW

**Comment by AtOMiCNebula** [comment]
Not sure how to put together a test for this, but if you have suggestions I'm all ears!  I found the issue originally because `Microsoft.ApplicationInsights` wasn't included, but the other two were found by looking closer at the DI container's `ServiceType`s; I have a light function app that might be able to be turned into a test, but it's tricky because not all types are present all the time (AppInsights is conditionally added to DI based on the presence of a telemetry key, for instance).

**Comment by AtOMiCNebula** [comment]
fyi @fabiocav, I see you're working on a similar issue in #4947 (but don't think it's quite the same).

**Comment by fabiocav** [comment]
@AtOMiCNebula thank you for the contribution! And for sharing the details on the issue, the issue makes sense.

The rule of thumb for this list is that relaxing (removing) dependencies is relatively safe, and something we've done in the past, but adding restrictions is something we'd only do in a major version release. Since the impact here is limited to scenarios where a deps file is used, we do have some flexibility, but we may have to introduce a slightly different way to handle those dependencies (which is something we have considered in the past).

**Comment by AtOMiCNebula** [comment]
@fabiocav I'm not surprised to hear you say this should be treated like a potential breaking change, but I didn't want to put words in your mouth either.  Sounds like an understandable concern either way though. :innocent:

Is there a "quirking"-type facility that could be leveraged here, such that if a quirk is enabled, it adds these additional entries to the runtime assemblies list?  Perhaps a local.settings.json/appSettings switch?  Alternatively, what's the timeline for cutting new major version releases?  Or, since you know the system better than I do, are there additional workarounds I didn't mention in my bug that might be applicable?

**Comment by AtOMiCNebula** [comment]
To make this less of a breaking change, I can update `DependencyHelper.GetRuntimeAssemblies` to check for an additional runtimeassemblies.json payload in an environment variable.  No effect for anyone who doesn't have it, but still unclear errors for those affected by it.  Happy to work that up if you think it's a more realistic short-term fix.

**Comment by fabiocav** [comment]
@AtOMiCNebula we do support the notion of feature flags, allowing us to put the new behavior behind something like that. Discoverability is sometimes a challenge with that, but at least it enables a good workaround. 

A new major version will be in public preview next month, so that would also be a good opportunity to do this (with actual GA in Q1 2020). 

I do have a couple of ideas on different policy behaviors we could support to make this a bit safer, but would need to flush some of the details out.

**Comment by AtOMiCNebula** [comment]
Sure thing!  Let me know if there's a preview branch I can retarget this PR towards.  I've found a workaround we can live with for now, so I'm not quite as annoyed with this bug as I was last week. :)

**Comment by fabiocav** [comment]
Closing stale PR. Please reopen if still relevant.

**Pull request closed without merging**
