### PR TITLE
[pack] Changed output path for Metadata.json

### PR DESCRIPTION
**Pull request by yojagad**
### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]
LGTM! 
Follow up question :  Build scripts for V4 have produce metadata.json as well?

cc @brettsam

**Comment by yojagad** [comment]
> Follow up question : Build scripts for V4 have produce metadata.json as well?

For hotfixes/patches alone, yes. The Antares change largely relies on it's presence.

**Comment by pragnagopa** [comment]
Thanks! Good to know V4 has this change as well. Please send a PR for V4 branch to fix the path if not already fixed

**Comment by yojagad** [comment]
> Thanks! Good to know V4 has this change as well. Please send a PR for V4 branch to fix the path if not already fixed

I misread/misunderstood the question. No , none of these changes have been ported over to v4 right now. I meant, v4 has to have metadata.json if it produces patches as well.

**Comment by pragnagopa** [comment]
> I misread/misunderstood the question. No , none of these changes have been ported over to v4 right now. I meant, v4 has to have metadata.json if it produces patches as well.

Can you please port these changes to V4 as well. From platform perspective, it would be good to address them together to avoid delaying the changes for V4 patches

**Comment by yojagad** [comment]
> > I misread/misunderstood the question. No , none of these changes have been ported over to v4 right now. I meant, v4 has to have metadata.json if it produces patches as well.
> 
> Can you please port these changes to V4 as well. From platform perspective, it would be good to address them together to avoid delaying the changes for V4 patches

It's not a direct port. It needs a separate set of changes... and additional investigation since folder names/versions have `-preview` on them. (For one, it Version.TryParse() on the versioning format doesn't work on Antares).

I'll do additional investigations on them.

**Comment by yojagad** [comment]
> > > I misread/misunderstood the question. No , none of these changes have been ported over to v4 right now. I meant, v4 has to have metadata.json if it produces patches as well.
> > 
> > 
> > Can you please port these changes to V4 as well. From platform perspective, it would be good to address them together to avoid delaying the changes for V4 patches
> 
> It's not a direct port. It needs a separate set of changes... and additional investigation since folder names/versions have `-preview` on them. (For one, it Version.TryParse() on the versioning format doesn't work on Antares).
> 
> I'll do additional investigations on them.

The other option is to assume `-preview` will go away soon and therefore no need to add additional logic to handle that. Once v4 starts getting versions like `4.0.0`, `4.1.0`, etc... Antares changes will continue to work as is.

I can incorporate changes in v4.x with that assumption if that works , let me know

**Comment by pragnagopa** [comment]
> The other option is to assume -preview will go away soon and therefore no need to add additional logic to handle that. Once v4 starts getting versions like 4.0.0, 4.1.0, etc... Antares changes will continue to work as is.

Let's port the changes needed for RU patching assuming `-preview` will be removed in next few months

**Pull request merged**
