### PR TITLE
Update java worker with new package name

### PR DESCRIPTION
**Pull request by pragnagopa**
Update java worker with new package name

### CODE REVIEW

**Comment by pragnagopa** [comment]
@mhoeger - Will update the PR to pull in the latest from protobuf repo once https://github.com/Azure/azure-functions-language-worker-protobuf/pull/10 is merged in.

**Comment by mhoeger** [comment]
@pragnagopa here's the node worker change! https://github.com/Azure/azure-functions-nodejs-worker/pull/71

I think this was already your plan, but should we wait on this PR until that is merged and published?

**Comment by pragnagopa** [comment]
@mhoeger - We need to update nodejs worker and publish to nuget. I can then update this PR to include worker updates.

**Comment by pragnagopa** [comment]
cc: @fabiocav @paulbatum 

**Breaking changes to Java Functions**

Updates to Annotations package
- Updated package name for Azure Funcitons Annotations to **com.microsoft.azure.functions.annotation** to be consistent with rest of the azure functions libraries and SDKs.
- Annotations with new package name is published to **azure-functions-library.jar**. Any further updates to annotations will only be published to this package.

To consume the latest functions runtime, following changes need to be made to existing java functions:

Changes needed to import statements in the function code:

Before

```
import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;
```
After (remove **serverless**):

```
import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;
```

Changes needed to pom.xml: **Update groupId, artificatId and version**
Before
```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-functions-java-core</artifactId>
            <version>1.0.0-beta-2</version>
</dependency>
```
After
```
<dependency>
      <groupId>com.microsoft.azure.functions</groupId>
        <artifactId>azure-functions-java-library</artifactId>
        <version>1.0.0-beta-4</version>
</dependency>
```

Please note that, we recommend pinning to the older runtime until azure-functions maven plugin is updated to consume azure-functions-library.jar. We will update this page once the maven plugin is updated

**Pull request merged**
