### PR TITLE
Update Java Worker Version to 2.15.0

### PR DESCRIPTION
**Pull request by shreyas-gopalakrishna**
Java Worker Release note [2.15.0](https://github.com/Azure/azure-functions-java-worker/releases/tag/2.15.0)

### CODE REVIEW

**Comment by kshyju** [comment]
@shreyas-gopalakrishna  Can you rebase? There was recent fixes to the secret repository tests.

**Comment by shreyas-gopalakrishna** [comment]
Tagging @kamperiadis as she is handling the release

**Comment by kamperiadis** [comment]
Done rebasing. Thank you @kshyju

**Review by jviau — APPROVED** [review]

**Review by surgupta-msft — APPROVED** [review]

**Comment by kamperiadis** [comment]
Thank you for approving the PR @jviau and @surgupta-msft Just rebased with the latest and was wondering if you could please merge the PR whenever you get a chance. Thank you!

**Pull request merged**
