### PR TITLE
Update PowerShell Worker to 3.0.1272

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
### Issue describing the changes in this PR

resolves https://github.com/Azure/azure-functions-host/issues/7906

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
Hi @liliankasem / @brettsam -- Looks like the `dev` branch is now pointing to `V4`. Is this the right branch target `V3`?

**Review by AnatoliB — APPROVED** [review]
LGTM

**Comment by liliankasem** [comment]
> Hi @liliankasem / @brettsam -- Looks like the `dev` branch is now pointing to `V4`. Is this the right branch target `V3`?

Yup!

**Review by liliankasem — APPROVED** [review]

**Comment by Francisco-Gamino** [comment]
> > Hi @liliankasem / @brettsam -- Looks like the `dev` branch is now pointing to `V4`. Is this the right branch target `V3`?
> 
> Yup!

Thanks! Merging PR.

**Pull request merged**
