### PR TITLE
Rename proto file under proper folder structure

### PR DESCRIPTION
**Pull request by mhoeger**
~Proto~ => azure-functions-language-worker-protobuf

### CODE REVIEW

**Comment by ahmelsayed** [comment]
Linux build is still failing https://ci.appveyor.com/project/appsvc/azure-functions-host-l70a7/build/2.0.9

It points to this [line](https://github.com/mhoeger/azure-webjobs-sdk-script/blob/1a82638d8c453a6b395b808504a92c69d8d038b1/src/WebJobs.Script.Grpc/generate_protos.sh#L51)

**Comment by mhoeger** [comment]
My bad - thanks for catching that! @ahmelsayed - it should be fixed now and there shouldn't be any other references to the "Proto" folder

**Comment by pragnagopa** [comment]
Thanks for adding linux builds. We have a .sh file that is only used on linux builds. Windows uses .bat file.

**Comment by ahmelsayed** [comment]
last push from @mhoeger looks good on my linux box. https://ci.appveyor.com/project/appsvc/azure-functions-host-l70a7/build/2.0.12 is still building it though.

**Comment by ahmelsayed** [comment]
I think maybe I know now what caused the initial odd [`src\WebJobs.Script.Grpc\Proto`](https://github.com/Azure/azure-functions-host/tree/992d4899d91abc5485fe19a77e2df152cadd244b/src%5CWebJobs.Script.Grpc%5CProto) folder to be created. You probably did

```
git subtree add --prefix src\WebJobs.Script.Grpc\Proto ...
```

it should be 
```
git subtree add --prefix src/WebJobs.Script.Grpc/Proto ...
```

**Comment by mhoeger** [comment]
I think you're on the subtree instructions!! thank for the verification ahmed

**Pull request merged**
