### PR TITLE
Release Java worker 1.8.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by amamounelsayed**
### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by TsuyoshiUshio — CHANGES_REQUESTED** [review]
https://github.com/Azure/azure-functions-host/blob/dev/release_notes.md
Do we need release note?

**Review by TsuyoshiUshio — APPROVED** [review]
LGTM

**Comment by amamounelsayed** [comment]
> https://github.com/Azure/azure-functions-host/blob/dev/release_notes.md
> Do we need release note?

It is added. Thank you so much sir

**Pull request merged**
