### PR TITLE
[Pack]Update Azure.Storage.Blobs to 12.9.0

### LINKED ISSUE #7455: Update host Azure.Storage.Blobs dependency to 12.9.0
Azure Storage Blobs SDK has received reliability improvements in the [12.9.0 release](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Blobs_12.9.0/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md#1290-2021-06-08) - functions host currently references 12.8.1 and should be updated.

### PR DESCRIPTION
**Pull request by paulbatum**
Includes version bump for related Azure.Core and Azure.Identity libraries

### Issue describing the changes in this PR

resolves https://github.com/Azure/azure-functions-host/issues/7455

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by paulbatum** [comment]
cc @brettsam FYI

**Comment by paulbatum** [comment]
I will update this PR with a new deps file to address the test failure once I've gotten an approval. Here's the dependency changes shown in the failed test:

```
  Changed:
    - Azure.Core.dll: 1.9.0.0/1.900.21.10502 -> 1.15.0.0/1.1500.21.30304
    - Azure.Identity.dll: 1.3.0.0/1.300.20.56202 -> 1.4.0.0/1.400.21.26202
    - Azure.Storage.Blobs.dll: 12.8.1.0/12.800.121.17902 -> 12.9.0.0/12.900.21.30804
    - Azure.Storage.Common.dll: 12.7.1.0/12.700.121.17902 -> 12.8.0.0/12.800.21.30804
    - Microsoft.Identity.Client.dll: 4.22.0.0/4.22.0.0 -> 4.30.1.0/4.30.1.0
    - Microsoft.Identity.Client.Extensions.Msal.dll: 2.16.5.0/2.16.5.0 -> 2.18.4.0/2.18.4.0
    - System.Memory.Data.dll: 1.0.1.0/1.0.120.56602 -> 1.0.2.0/1.0.221.20802

  Removed:

  Added:
    - System.Text.Encodings.Web.dll: 4.0.5.1/4.700.21.11602
```

**Comment by brettsam** [comment]
/cc @fabiocav as I think we had some other incident related to `System.Text.Encodings.Web`.

@paulbatum -- do you know where that came in from? Did storage add it?

>  Added:
    - System.Text.Encodings.Web.dll: 4.0.5.1/4.700.21.11602

**Comment by paulbatum** [comment]
Let me update the dependencies step by step to figure out what introduced it.

**Comment by karshinlin** [comment]
Do we need to add "System.Text.Encodings.Web.dll" to src/WebJobs.Script/Description/DotNet/ScriptFunctionMetadataResolver.cs ? This was done when I originally brought v12 dependencies in. 

To @brettsam's point, we have a recent PR related to System.Text.Encodings.Web.dll here: https://github.com/Azure/azure-functions-host/commit/6679007bbf39dbc6e77c38219bcbf3841fdb4bfb

**Comment by fabiocav** [comment]
The issue around `System.Text.Encodings.Web` was about compliance with a CVE recommendation. This is already fulfilled as an SDK dependency at runtime. As long as we're following this, we're good: https://github.com/dotnet/runtime/issues/49377

**Comment by paulbatum** [comment]
Azure.Core added System.Text.Encodings.Web as a dependency in 1.13.0. 

I did a before and after comparison looking at the loaded modules - there is no change. In both cases, this assembly is loaded from `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.16\`

**Comment by paulbatum** [comment]
I've updated the PR with a new deps file. Please take a look.

**Review by brettsam — DISMISSED** [review]
Looks like there's a conflict, but other than that, looks good.

**Review by brettsam — DISMISSED** [review]

**Review by pragnagopa — APPROVED** [review]

**Pull request merged**
