### PR TITLE
Load disabled functions last

### PR DESCRIPTION
**Pull request by mhoeger**
Resolves https://github.com/Azure/azure-functions-host/issues/4963
Causes unnecessary bump in cold start times

### CODE REVIEW

**Comment by fabiocav** [comment]
Missed commenting on this in the issue, but disabled functions are still "invocable" using the portal and admin endpoints, this changes that behavior. Was that discussed?

**Comment by mhoeger** [comment]
@fabiocav - got it :\ luckily a test caught that too! Finbar reported this as an issue because a customer ran into slow perf from lingering disabled functions that took a long time to load.

I put out this PR when I was going through old issues since it looked like a pretty quick and easy fix. I'm guessing even non-http triggered functions are "invocable" through the Portal? I'm ok closing this PR and marking the issue as "wont-fix" as long as invocation that behavior's supported.

Let me know what you think!

**Comment by AartBluestoke** [comment]
If the complaint is time to active functions being available, perhaps and ordering could be applied ; boot the active functions, then the disabled ones?

**Comment by mhoeger** [comment]
Good suggestion, thansk @AartBluestoke ! 

@fabiocav - could you please review?

**Pull request merged**
