### PR TITLE
Fixing flaky test

### PR DESCRIPTION
**Pull request by pragnagopa**

### CODE REVIEW

**Comment by pragnagopa** [comment]
This test is failing in master

**Comment by brettsam** [comment]
was it failing in dev as well?

**Comment by pragnagopa** [comment]
> was it failing in dev as well?

No did not fail in dev. But I could repro it locally when I ran the test multiple times 

Current test run aborted with. Will investigate:
```
The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: WorkerCofig for runtime:  not found
At C:\azure-webjobs-sdk-script\run-tests.ps1:21 char:5
+     & dotnet $cmdargs | Out-Host
+     ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The active test...ime:  not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerChannelFactory.CreateLanguageWorkerChannel(String scriptRootPath, St
ring runtime, IMetricsLogger metricsLogger, Int32 attemptCount, IOptions`1 managedDependencyOptions) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\LanguageWorkerChannelFactory.cs:line 40
   at Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\FunctionRegistration\FunctionDispatcher.cs:line 107
   at Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher.RestartWorkerChannel(String runtime, String workerId) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\FunctionRegistration\FunctionDispatcher.cs:line 269
   at Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher.WorkerError(WorkerErrorEvent workerError) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Rpc\FunctionRegistration\FunctionDispatcher.cs:line 261
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by pragnagopa** [comment]
cc @divyagandhii

**Comment by pragnagopa** [comment]
cc @gzuber

**Pull request merged**
