### PR TITLE
[BreakingChangeAnalysis]Update loglevel to Debug

### PR DESCRIPTION
**Pull request by pragnagopa**
### Issue describing the changes in this PR
Logs from breaking change analysis show up in user logs causing confusion. This PR changes all logs to debug level as the logs are only relevant for internal analysis

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by pragnagopa** [comment]
cc @FinVamp1

**Comment by fabiocav** [comment]
Closing stale PR. If this work is still relevant, can you please rebase, reopen and engage reviewers? Thank you!

**Comment by ravibha** [comment]
Hi,
We are still seeing the issue mentioned here related to the logging of NotSupportedException: https://docs.microsoft.com/en-us/answers/questions/28681/what-is-this-message-breaking-change-analysis-oper.html

This creates noise in the telemetry. Should we upgrade to the latest sdk, or do we need for this change to go in?

Thanks

**Comment by pragnagopa** [comment]
New PR: https://github.com/Azure/azure-functions-host/pull/7466 to remove breaking change analysis

**Comment by ravibha-hub** [comment]
Hi @pragnagopa ,
Is this now checked in? Is there a package I need to upgrade for fixing this on my end?

Thanks!

**Comment by pragnagopa** [comment]
@ravibha-hub  - Changes are rolled out to production. V3 function apps running on latest version - 3.1.3.0 or higher should not see logs from breaking change analysis

**Comment by ravibha-hub** [comment]
Thanks!

**Pull request closed without merging**
