### PR TITLE
Fix proxy behavior

### LINKED ISSUE #6198: [Regression]Fix proxy behavior
Today, ScriptHost.cs iterates through the list of descriptorProviders to try and create the right one for each FunctionMetadata.
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L694 

If a function exists with a proxy, as long as the ProxyFunctionDescriptorProvider is evaluated first, invocations for proxy go through the correct invoker. However, if WorkerFunctionDescriptorProvider is evaluated first for some reason, proxy requests would go through the wrong invoker and therefore fail.

### PR DESCRIPTION
**Pull request by yojagad**
Fixes #6198

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]
cc @ankitkumarr fyi

**Comment by fabiocav** [comment]
I think the issue description is somewhat inaccurate, and I'm concerned about this change as it could break customers with ambiguous routes. Also, have you validated that the language evaluation does not exclude proxies for all of those descriptors?

**Comment by pragnagopa** [comment]
I am unsure about how this change effects dotnet functions (in-proc).  For out-of-proc, this change is safe as language workers do not load/handle invocations for proxies

**Comment by yojagad** [comment]
Adding a little more context here as discussed in the call. I verified that the order of evaluation before the commit here https://github.com/Azure/azure-functions-host/commit/621df2c50b5ab96dbd403d173161a4d7820d02c0 with a function that has a proxy as well, is the ProxyFunctionDescriptorProvider followed by WorkerFunctionDescriptorProvider. With the afore mentioned commit , WorkerFunctionDescriptorProvider was getting evaluated first thus routing proxies to the wrong route.

I added E2E tests for HttpWorker and RpcWorker scenarios to catch any ordering regression going forward 

proxies.json
https://github.com/Azure/azure-functions-host/blob/dev/sample/HttpWorker/proxies.json https://github.com/Azure/azure-functions-host/blob/dev/sample/Node/proxies.json

E2E tests.
https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/SamplesEndToEndTests_HttpWorker.cs#L38 
https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/SamplesEndToEndTests_Node.cs#L120

**Comment by mhoeger** [comment]
Does the functionMetadata of a proxy function have a `Language` associated with it btw? I'm surprised that there are instances of matches based off of the language!

**Comment by pragnagopa** [comment]
@mhoeger - Fix was specific to HttpWorker as language is null  and it could a proxy. @fabiocav pointed out what you mentioned, language is not set for a proxy. 

@yojagad  sent a follow up PR to remove redundant checks.

**Comment by yojagad** [comment]
Also, looking at the proxies.json schema, it doesn't look like it http://json.schemastore.org/proxies

**Comment by fabiocav** [comment]
@mhoeger we've sync'd up offline. recommended changes will be made and this was originally opened in response to a regression, so this is restoring the previous behavior.

**Pull request merged**
