### PR TITLE
Update function execution event log with invocation details

### PR DESCRIPTION
**Pull request by divyagandhisethi**
### Issue describing the changes in this PR

We are publishing function execution count metric for Linux EP/AppService skus to Azure monitor. The metering service needs events from the functions host to publish the  execution event to MDM.  Issue #8228 

### Pull request checklist

* [X] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [X] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [X] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [X] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by pragnagopa** [comment]
Please add logs from private stamp E2E testing

**Comment by pragnagopa** [comment]
@CooperLink will be testing the fix on private stamp

**Comment by CooperLink** [comment]
I verified this on my private stamp.  It works and we should move forward with updating host . 
https://msazure.visualstudio.com/Antares/_workitems/edit/14203962

**Review by CooperLink — APPROVED** [review]
This change should make FunctionExecutionCount work on Linux Dedicated and EP. Also should make platform respond more consistently to the metric from EP and Consumption

**Review by pragnagopa — CHANGES_REQUESTED** [review]
@divyagandhisethi - please add unit tests. Also confirm if this change is safe to merge before ANT 98 deployment

**Comment by CooperLink** [comment]
Is there any chance that not reporting timestamp breaks Ant97 apps? We use the timestamp currently to report status to DataService. It might make sense to have the logger log two lines. One schema-tized and one timestamp.  Or perhaps better to wait until we verify 98 rollout in a stamp before pushing this change there.  

Otherwise we risk making it so ANT97 stamps can no longer get LatestActivityTimestamp to report to DataService

**Comment by pragnagopa** [comment]
Converting this PR to draft as we need to wait for ANT 98 deployment to complete ETA ~ end of may

**Comment by pragnagopa** [comment]
@divyagandhisethi - ANT 98 roll out is almost complete. 

-	Please rebase this PR on the latest changes in dev
-	Add Unit tests
-	Update PR description with logs on Private Stamp verification
-	Send cherry-pick PR to v3.x

**Comment by fabiocav** [comment]
@divyagandhisethi safe to assume this is ready for review at this point?

**Comment by divyagandhisethi** [comment]
> @divyagandhisethi safe to assume this is ready for review at this point?

Yes the change is complete, but it seems to be failing some tests at this point - so need to resolve those before signoff. Will ping you for final review.

**Comment by divyagandhisethi** [comment]
> > @divyagandhisethi safe to assume this is ready for review at this point?
> 
> Yes the change is complete, but it seems to be failing some tests at this point - so need to resolve those before signoff. Will ping you for final review.

@fabiocav This is now ready for review.

**Review by pragnagopa — APPROVED** [review]

**Pull request merged**
