### PR TITLE
Upgrade App Service Authentication/Authorziation nuget package

### PR DESCRIPTION
**Pull request by ConnorMcMahon**
Upgrade the Authentication/Authorization .NET Core middleware ensuring
that the latest fixes and features are present for Linux Consumption, as
well as utilizing the new logging schema for internal telemetry.

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [x] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [x] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by ConnorMcMahon** [comment]
@brettsam or @fabiocav, I need some help fixing the dependency test. It looks like most of the differences from my bin directory vs the one expected in tests is various tiny WebJobs dependency differences, along with the changes related to the fact that I changed the versions of the nuget package and it's internal nuget dlls.

The one thing that looks problematic is that currently my Functions package take a dependency on `Microsoft.Extensions.Caching.Memory` v2.2.0, instead of 2.1.0 like the current deps file depends on.

**Comment by brettsam** [comment]
These look okay -- this is a "double-check before updating packages" step since we've been burned by this before. You can fix this by building locally and then copying your `...WebHost.deps.json` file from the WebHost bin folder over the one in the test directory here: https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests/Microsoft.Azure.WebJobs.Script.WebHost.deps.json, and including that as part of your PR.

```
The dependencies in WebHost have changed and should be reviewed before proceeding. Follow up with brettsam or fabiocav for next steps.

Previous file: D:\a\1\s\test\WebJobs.Script.Tests\bin\Debug\netcoreapp3.1\Microsoft.Azure.WebJobs.Script.WebHost.deps.json
New file:      D:\a\1\s\src\WebJobs.Script.WebHost\bin\Debug\netcoreapp3.1\Microsoft.Azure.WebJobs.Script.WebHost.deps.json

Changed:
- Microsoft.Azure.AppService.Middleware.Functions.dll: 1.0.0.0/1.0.0.0 -> 1.4.0.0/1.4.0.0
- Microsoft.Azure.AppService.Middleware.Modules.dll: 1.3.4.0/1.3.4.0 -> 1.4.0.0/1.4.0.0
- Microsoft.Azure.AppService.Middleware.NetCore.dll: 1.0.0.0/1.0.0.0 -> 1.4.0.0/1.4.0.0

Removed:

Added:

```

**Comment by brettsam** [comment]
I just noticed your comment about Caching.Memory -- I don't see that showing up. Can you tell it's in the new deps.json?

**Comment by ConnorMcMahon** [comment]
@brettsam, yeah that is where I saw the change. I will update the PR so you have visibility with this, and we can discuss if it is acceptable then.

**Review by brettsam — APPROVED** [review]

**Review by madelinegordon — APPROVED** [review]

**Pull request merged**
