### PR TITLE
Updated Binding Redirects for FSharp.Core

### PR DESCRIPTION
**Pull request by Angr1st**
#4005
I see that you seem to have a lot on your plate but I have taken the liberty of updating the FSharp.Core references to the newest version that is available currently.

### CODE REVIEW

**Comment by Angr1st** [comment]
I haven't actually found any real reference to FSharp.Core inside of the Solutions. Would it be possible to completely drop the binding redirects for it and let it be handled completely by the consumers of Azure Functions as it is generally suggested to bring your own FSharp.Core.

**Comment by Angr1st** [comment]
@cartermp would you know who could review this?

**Comment by Angr1st** [comment]
I also wanted to mention that Amazon Serverless Applications let us bring our own FSharp.Core. 
awsservfsharp

**Comment by fabiocav** [comment]
@Angr1st thank you for the patience with this. 

Those redirects are not really applicable in the host. The ones you found are applied to sample and test projects, the actual set of redirects that apply to the host would be defined in the Web.Config file for the WebHost project. We don't currently have any redirects for FSharp.Core there, and you should be able to bring in a different version of the dependency with  your functions. Are you finding that not to be the case? If so, can you share more details?

**Comment by Angr1st** [comment]
How strange it seemed to be an issue before but now with the newest version available today it just works. (FSharp.Core 4.5.0 & Microsoft.NET.SdK.Functions 1.0.26 & Function Runtime Version: 2.0.12408.0)  When I opened this issue it did not work I think. That should have been around Microsoft.NET.Sdk.Functions 1.0.24 and Function Runtime Version: 2.0.12285.0 I think. 
Which Web.Config? Is it located inside this repository? Could you point me to it?

Im closing this as it is not needed anymore.

**Pull request closed without merging**
