### PR TITLE
Jit Trace Update v3.5.0

### PR DESCRIPTION
**Pull request by VpOfEngineering**
Thank you to @eliaslopezgt for making this happen.

Updating the Linux and Windows JIT trace files for `v3.x` in anticipation of the next v3 release (`3.5.0`)

```
03:28:51 info: JitTraceGenerator.Services.Generator[0] JS Function JIT times. Initial: 298ms, Final: 67ms, Difference: 231ms
03:28:51 info: JitTraceGenerator.Services.Generator[0] DotNet Function JIT times. Initial: 207ms, Final: 18ms, Difference: 189ms
```

```
2022-02-15T22:16:57.381299Z	3.5.0.0	PreJIT Successful prepares: 5419, Failed prepares: 2 FileName = coldstart.jittrace
2022-02-15T22:11:57.378715Z	3.5.0.0	PreJIT Successful prepares: 5419, Failed prepares: 2 FileName = coldstart.jittrace
2022-02-15T22:06:57.3246807Z	3.5.0.0	PreJIT Successful prepares: 5419, Failed prepares: 2 FileName = coldstart.jittrace
```

### CODE REVIEW

**Comment by pragnagopa** [comment]
@eliaslopezgt - please update the PR description with Kusto logs that show successfull JIT prepares for Windows. Not a blocker. Good to have.

**Review by pragnagopa — APPROVED** [review]
@balag0 - do sign-off as well specifically for Linux Jit traces.

**Comment by safihamid** [comment]
Going forward, would you please paste the JIT time and JIT details from .coldstart file which is taken after jittrace file is updated? That way we can make sure we haven't missed anything and we can quickly verify by looking at that log.

**Comment by eliaslopezgt** [comment]
> Going forward, would you please paste the JIT time and JIT details from .coldstart file which is taken after jittrace file is updated? That way we can make sure we haven't missed anything and we can quickly verify by looking at that log.

The Jit times displayed in the description are parsed from the coldstart files from before running the node and dotnet function apps and afterwards.  Sure I can put the entire log. @safihamid

**Comment by eliaslopezgt** [comment]
> @eliaslopezgt - please update the PR description with Kusto logs that show successfull JIT prepares for Windows. Not a blocker. Good to have.

done. @pragnagopa

**Comment by safihamid** [comment]
@eliaslopezgt oh that's great! I didn't see those in the description section at first :). that's good enough! thanks!

**Review by safihamid — APPROVED** [review]

**Review by balag0 — APPROVED** [review]

**Pull request merged**
