### PR TITLE
Updating FileWatcherEventSource to avoid publishing events after dis…

### PR DESCRIPTION
**Pull request by fabiocav**
…posal. Throwing from ScriptEventManager if Publish or Subscribe are called after disposal.

### CODE REVIEW

**Comment by fabiocav** [comment]
Was seeing some test failures deeper in the stack. Putting those checks in place for now.

**Comment by brettsam** [comment]
It looks like I did something similar here: https://github.com/Azure/azure-functions-host/pull/2413, and ended up pulling it out after @mathewc's review. His argument was that we shouldn't be no-opping if disposed -- we should figure out why someone is calling a disposed object and fix that instead.

**Comment by fabiocav** [comment]
The change throws in the `ScriptEventManager` the no-op path now only applies to the `FileWatcherEventSource`, and the consumption is scoped to that class itself. It would only come from a possible race in disposing of the watcher.

**Comment by fabiocav** [comment]
@mathewc could you comment?

**Comment by mathewc** [comment]
Guys - sorry I missed this one. I'm fine with these changes if they help us get to the bottom of disposal issues.

**Pull request merged**
