### PR TITLE
Rename environment variable to set ConsoleLoggingMode

### LINKED ISSUE #2759: Don't use app settings with colons in them
There is this setting `host:logger:consoleLoggingMode=always` to log to the console. App Service doesn't allow `:` in the app setting name, making it pretty difficult to set. Either relax that in App Service or don't use such app settings in the host

### PR DESCRIPTION
**Pull request by pragnagopa**
Fixes #2759

### CODE REVIEW

**Comment by brettsam** [comment]
We may want to hold off on this. The DI changes coming (maybe next week?) will change how we read this configuration value. It'll come from IConfiguration directly, which we can configure to read from host.json, command line args, env vars, etc.

**Comment by pragnagopa** [comment]
Right now, for debugging python functions this is the only. I will go ahead merge this in. We can revisit how to console logger once DI changes are in?

**Comment by brettsam** [comment]
Yeah, that's okay. Just know that it may change yet again in the next couple of weeks :-)

**Comment by pragnagopa** [comment]
Yes. Will keep an eye on DI changes.
@asavaritayal / @ahmelsayed  - Dockerfiles that set this environment variable need to updated.

**Pull request merged**
