### PR TITLE
Add Python to placeholder pool list

### LINKED ISSUE #7599: Python is not included in the languages allowed for placeholder pools
#### Repro steps

In `ShouldStartAsPlaceholderPool`, if a worker runtime is set and placeholder mode is enabled, we check a list of languages to determine if we should start the placeholder language channel. Python is currently not on the list, when it should be.

#### Expected behavior

Python worker channel should start up in placeholder mode.

#### Actual behavior

Python worker channel does not start up in placeholder mode when a worker runtime is previously set to Python.

### PR DESCRIPTION
**Pull request by pgombar**
### Issue describing the changes in this PR

resolves #7599

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by pgombar** [comment]
Currently doing final round of validation on private stamp, will update here once that's done.

**Review by pragnagopa — DISMISSED** [review]

**Comment by pragnagopa** [comment]
Please add a unit test that verifies this list to ensure we do not accidentally add/remove from the list

**Comment by pgombar** [comment]
> Please add a unit test that verifies this list to ensure we do not accidentally add/remove from the list

@pragnagopa updated the existing unit test, thanks for that.

**Review by pragnagopa — APPROVED** [review]
👍

**Pull request merged**
