### PR TITLE
-Add support for java on linux placeholder

### PR DESCRIPTION
**Pull request by amamounelsayed**

### CODE REVIEW

**Comment by pragnagopa** [comment]
@divyagandhii  @anirudhgarg  @amamounelsayed 
Making sure you are aware of the consequences of this change:
- Customer's app insights logs will start showing more process killing logs i.e killing python and node for java etc
- Debounce killing two process at the same time will be taking compute away 

My recommendation would be to wait on the pool management feature @divyagandhii is working on in Antares

**Comment by amamounelsayed** [comment]
@pragnagopa  ACK 

I checked the processing with and without the java process with 1 core and 1GB ram and the average CPU computing is the same.

@divyagandhii When do you think the pool management feature will be in Antares?

**Comment by divyagandhii** [comment]
Fixes #4932

**Comment by divyagandhii** [comment]
We have decided to compare perf numbers with and without this change on private stamps. If we run into a perf issue, we can have a separate pool just for java.

**Comment by pragnagopa** [comment]
Please note that with this change, for a dotnet function app on linux consumption, we will start killing 2 processes at the same time: node, python and java. For perf test, make sure load test is run for atleast 10-15secs to ensure, site is under load during debouce process shutdown which happens around 5secs.

**Comment by amamounelsayed** [comment]
@pragnagopa Sounds good I will check with @divyagandhii what kind of test we can run. And keep the team update it.

**Comment by pragnagopa** [comment]
Note : this pr is not needed if using pools.

**Comment by amamounelsayed** [comment]
@pragnagopa In case we do not have enough machines in the pool, this is not the fall back image.

**Comment by pragnagopa** [comment]
Change is not needed for Fallback image either. Java.exe will after specialization.

**Comment by amamounelsayed** [comment]
@pragnagopa You are right, so in case we need to avoid the cold start for the fall back we may need it,but else we do not as the specialization will take care of it, I tested this scenario and it worked.

**Comment by pragnagopa** [comment]
That's correct. Pool management should take care of assigning best match for a given request. In case, there is no match, request should go to fallback image which has functions host up and running and a language worker process will start after specialization.

**Comment by pragnagopa** [comment]
I will go ahead close this PR for now. Please work with @divyagandhii on the timeline for pool management.

**Pull request closed without merging**
