### PR TITLE
Fixed minor typos

### PR DESCRIPTION
**Pull request by tony-xia**

### CODE REVIEW

**Comment by fabiocav** [comment]
Can you please consolidate all the spelling changes spread across the PRs into this one? Thanks!

**Comment by tony-xia** [comment]
i've consolidated all the spelling changes. thanks @fabiocav

**Review by fabiocav — APPROVED** [review]

**Comment by fabiocav** [comment]
Thank you! Flagging this as approved. Any chance you can squash the commits so we can merge this? Thanks again!

**Pull request closed without merging**
