### PR TITLE
[in-proc backport] Use dotnet common artifacts output (#9858)

### PR DESCRIPTION
**Pull request by jviau**
Backport of #9858

### CODE REVIEW

**Comment by liliankasem** [comment]
@jviau  Can you remove the `Update to .NET8 SDK` commit?

**Comment by jviau** [comment]
> @jviau Can you remove the `Update to .NET8 SDK` commit?

This functionality is only available in .NET8 SDK. We will also need this when mult-targeting net8 & net6 anyways.

I won't be checking this in until we resolve the docker build issue.

**Comment by liliankasem** [comment]
> > @jviau Can you remove the `Update to .NET8 SDK` commit?
> 
> This functionality is only available in .NET8 SDK. We will also need this when mult-targeting net8 & net6 anyways.
> 
> I won't be checking this in until we resolve the docker build issue.

Then I think this should be a separate PR, I think the backport PR should be purely backport only without any extra changes. We also want to put all .NET 8 changes into a feature branch first before bringing it all into in-proc. If it makes more sense, maybe these two PRs can point at the in-proc .net 8 feature branch

Edit: created a feature branch: https://github.com/Azure/azure-functions-host/tree/feature/in-proc8

**Comment by fabiocav** [comment]
If this is blocked by the docker issues, we need to consider bringing this change to the feature branch used for multi-targeting.

**Comment by jviau** [comment]
This was ported in another PR

**Pull request closed without merging**
