### PR TITLE
Update EasyAuth for Linux Consumption apps

### PR DESCRIPTION
**Pull request by ConnorMcMahon**
### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by ConnorMcMahon** [comment]
I'm not really sure how to address updating EasyAuth for Linux Consumption in the release notes. We generally have sparse release notes on the app service announcements page, so we could just include a link to those? @fabiocav, any suggestions?

**Comment by ConnorMcMahon** [comment]
We may want to add an exclusion to these EasyAuth dlls from this specific test, as I plan to make this change every time we do a new windows release for EasyAuth in the future, and I don't want to make this simple package reference change more work than it needs to be.

**Comment by fabiocav** [comment]
About the release notes: yeah, it's fine to add a comment and a link
Deps validation: We can exclude this dependency from the test. Also, looks like your deps.json update reformatted the file, so it's pretty difficult to review right now. Can you revert the format changes so we can spot your actual changes here?

Thanks!

**Comment by ConnorMcMahon** [comment]
Just a friendly ping for review approval here.

**Comment by ConnorMcMahon** [comment]
Friendly ping here for approval now that feedback addressed.

**Review by madelinegordon — APPROVED** [review]

**Pull request merged**
