### PR TITLE
Updating NuGet.ProjectModel to 5.11.6

### PR DESCRIPTION
**Pull request by soninaren**
### Issue describing the changes in this PR

Updating the Nuget project model version. Updating deps.json file.

resolves #issue_for_this_pr

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Review by brettsam — APPROVED** [review]

**Review by fabiocav — APPROVED** [review]

**Review by fabiocav — COMMENTED** [review]
Approved, but this will likely require an update to deps tests.

**Comment by soninaren** [comment]
Updating the following dependencies
```
Previous file: D:\a_work\1\s\test\WebJobs.Script.Tests\bin\Debug\net6.0\Microsoft.Azure.WebJobs.Script.WebHost.deps.json
New file:      D:\a_work\1\s\src\WebJobs.Script.WebHost\bin\Debug\net6.0\Microsoft.Azure.WebJobs.Script.WebHost.deps.json


Changed:
- NuGet.Common.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.Configuration.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.DependencyResolver.Core.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.Frameworks.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.LibraryModel.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.Packaging.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.ProjectModel.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.Protocol.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1
- NuGet.Versioning.dll: 5.11.5.1/5.11.5.1 -> 5.11.6.1/5.11.6.1


Removed:
```

**Pull request merged**
