### PR TITLE
Fix runtime version telemetry logging

### PR DESCRIPTION
**Pull request by divyagandhii**
This change fixes telemetry for the small number of apps where the FUNCTIONS_WORKER_RUNTIME app setting is missing.

When the FUNCTIONS_WORKER_RUNTIME app setting is not set, the platform also does not set the FUNCTIONS_WORKER_RUNTIME_VERSION environment variable during specialization.  Eventually this causes us to report incorrect runtime version for these apps.  The fix here is to not report the version at all for such apps and just report the runtime. So for ex: instead of "dotnet-3.6" it would just be "dotnet" for these misconfigured apps.

### CODE REVIEW

**Comment by Hazhzeng** [comment]
@divyagandhii Also, we need a same PR for V3

**Comment by fabiocav** [comment]
@divyagandhii can you share more details on the change?

Do we have a sample of what the new output will look like so we can provide this to the analytics team for validation?

@jcookems can you please also comment on the change an the output in the test here:
https://github.com/Azure/azure-functions-host/pull/5680/files#diff-8467b5846f50cf74bbff85a90429518eR409-R418

**Comment by fabiocav** [comment]
Aslo, before having this merged, have you been able to validate in a test environment?

**Comment by divyagandhii** [comment]
> 
> 
> Aslo, before having this merged, have you been able to validate in a test environment?

yes we tested this in a local container.

**Comment by jcookems** [comment]
Looks good to me

**Pull request merged**
