### PR TITLE
[Backport] [Linux Consumption] Publish Specialization complete event

### PR DESCRIPTION
**Pull request by balag0**
Backporting https://github.com/Azure/azure-functions-host/commit/69e70a87bad28453bae43715c1e7a5ee8893cf37
Also had to cherry-pick dependent commit https://github.com/Azure/azure-functions-host/commit/c73bc1510fbff3e936cfa4dd788a86ff9b29c90e

resolves https://github.com/Azure/azure-functions-docker-private/issues/136

### Pull request checklist

* [ X] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ X] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ X] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ X] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

### CODE REVIEW

**Comment by pragnagopa** [comment]
We will not be releasing V2 anymore. Auto-upgrade completed!

**Comment by fabiocav** [comment]
@balag0 / @pragnagopa is this still required? This is for 2.0 only

**Comment by balag0** [comment]
Yes required. I will be working on this.

**Comment by fabiocav** [comment]
@balag0 closing this as there has been no activity. Feel free to keep the branch and reopen this when ready for review.

Thanks!

**Pull request closed without merging**
