### PR TITLE
Add Python worker to script csproj

### PR DESCRIPTION
**Pull request by ahmelsayed**

### CODE REVIEW

**Comment by pragnagopa** [comment]
@ahmelsayed  - Can you please provide description on why this change is needed?

**Comment by ahmelsayed** [comment]
@fabiocav mentioned removing the direct reference for the workers from the core-tools and relying only on the transient dependency coming through the host. We will need all the workers to be here for that, right?

**Comment by fabiocav** [comment]
Indeed. This came up again today.

**Comment by pragnagopa** [comment]
@ahmelsayed  - can you add link to code for Microsoft.Azure.Functions.PythonWorkerRunEnvironments project?

**Comment by ahmelsayed** [comment]
@maiqbal11 would know.

**Comment by maiqbal11** [comment]
> @ahmelsayed - can you add link to code for Microsoft.Azure.Functions.PythonWorkerRunEnvironments project?

This lives as part of the CI script for the python worker: https://github.com/Azure/azure-functions-python-worker/blob/dev/azure-pipelines.yml. The section to generate this is at the end.

**Comment by fabiocav** [comment]
Closing this as it has been sitting for a while and conflicts need to be resolved. Please reopen if still relevant.

**Pull request closed without merging**
