### PR TITLE
Add PowerShell function artifacts for perf test

### PR DESCRIPTION
**Pull request by daxian-dbw**
Reopen the PR after moving changes to the refactored perf testing code.

Add the necessary PowerShell function artifact to on board PowerShell worker to the perf test. /cc @alrod
I will need help from @alrod to author the .jmx file for PowerShell and finish the rest on-boarding steps.

/cc @TylerLeonhardt @SteveL-MSFT @pragnagopa

### CODE REVIEW

**Comment by alrod** [comment]
You alaso need to add the test definition here: https://github.com/Azure/azure-functions-host/blob/dev/tools/WebJobs.Script.Performance/WebJobs.Script.Performance.App/PerformanceManager.cs#L43

**Comment by daxian-dbw** [comment]
The test definition for powershell has already been added.

**Comment by alrod** [comment]
Please comment test args and squash commits to one

**Comment by daxian-dbw** [comment]
@alrod test args was commented out and the commits were squashed. I think it's ready to be merged.
Thanks for the help to enable powershell in throughput test!

**Comment by daxian-dbw** [comment]
@alrod I was on vacation and just notice this PR hasn't been merged. You made changes to how test functions are deployed, which caused conflicts to this PR.
Can you please advise where the PowerShell test functions should be placed after your change?

**Comment by alrod** [comment]
> @alrod I was on vacation and just notice this PR hasn't been merged. You made changes to how test functions are deployed, which caused conflicts to this PR.
> Can you please advise where the PowerShell test functions should be placed after your change?

@daxian-dbw, I changed deployment to use run-from-zip. So now you just need to provide a zip with your powershell function.

**Comment by daxian-dbw** [comment]
Where will that zip file be deployed? Put it differently, how do I provide the zip file?

**Comment by daxian-dbw** [comment]
Chatted with @alrod offline and the PS function zip file has been sent to @alrod. So close this PR.

**Pull request closed without merging**
