### PR TITLE
Fully shutdown host on function timeout

### PR DESCRIPTION
**Pull request by wilsonge**
Using the same fix from https://github.com/Azure/azure-functions-host/commit/f308acc1b8dc72018475fafa9075395b2e1186cc

At the moment if timeout is expired, then the function app keeps running but there is no host available to consume requests as we stop it here: https://github.com/wilsonge/azure-functions-host/blob/0c1cd929a9411d3a1523eab41d56c2bf70c9d6af/src/WebJobs.Script.WebHost/WebScriptHostExceptionHandler.cs#L48

### CODE REVIEW

**Comment by paulbatum** [comment]
@mhoeger I'm not sure, this change looks like it might be correct to me. When a timeout occurs we force the process to shutdown. Another request will wake everything back up again. @brettsam and @fabiocav understand this best so we need them to review.

However I will note that this PR is targeting master which is not correct. It should be against dev.

**Comment by wilsonge** [comment]
Changed the base branch. I'll wait for a consensus on whether this is/isn't the fix :)

**Comment by mhoeger** [comment]
Just synced with @fabiocav. It looks like the ideal change is to do `HostingEnvironment.InitiateShutdown();`, which adds a layer of abstraction and lets us shut things down in a smarter way. We can't do this yet because of some work around dependency injection that's still in progress. 

All that being said, @wilsonge, this change is in the right direction and would be helpful to have! Would you mind changing your PR to not delete the TODO comments though?

**Comment by george-wilson-iproov** [comment]
@mhoeger can i prod for an update on this please?

**Comment by wilsonge** [comment]
thanks :)

**Comment by wilsonge** [comment]
Cheers guys!

**Pull request merged**
