### PR TITLE
JitTrace updates for v4.2.0

### PR DESCRIPTION
**Pull request by eliaslopezgt**
# Updating the Linux and Windows JIT trace files for v4.x in anticipation of the next v4 release (4.2.0)

Windows JitTrace generator log:
```
22:21:32 info: JS Function JIT times. Initial: 793, Final: 53, Difference: 740
22:21:32 info: DotNet Function JIT times. Initial: 346, Final: 16, Difference: 330
```

Linux JitTrace log:
```
Total lines in latest windows jittracefile = 6919
Total lines in current jittracefile = 6829
Total lines in new jittracefile = 4680
3788 duplicates were skipped
Total lines in updated jittracefile = 6848
```

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by pragnagopa — DISMISSED** [review]
👍

**Comment by safihamid** [comment]
@eliaslopezgt something doesn't make sense. 
Total lines in current jittracefile = 6829
Total lines in updated jittracefile = 20837

Are you saying for Linux we have ~14,000 new lines? This causes memory usage to go up specially if those method calls are not necessary.

What are these numbers for Linux V3?

**Comment by eliaslopezgt** [comment]
> @eliaslopezgt something doesn't make sense. Total lines in current jittracefile = 6829 Total lines in updated jittracefile = 20837
> 
> Are you saying for Linux we have ~14,000 new lines? This causes memory usage to go up specially if those method calls are not necessary.
> 
> What are these numbers for Linux V3?

Unfortunately, I didn't keep the stats for v3, I can tell you that v3 linux.coldstart.jittrace has 8840 lines.

**Comment by eliaslopezgt** [comment]
@safihamid I had put a delay between launching the Host and the execution of miniantares to accomodate for the host starting, I should have put this delay before launching perfview and not after.  I did this only for v4, since it takes more time to start than v3.
I corrected the problem, but still we are talking about an increment of 10k lines from the last linux.coldstart.jittrace.
```
Total lines in latest windows jittracefile = 6919
Total lines in current jittracefile = 6829
Total lines in new jittracefile = 15498
4583 duplicates were skipped
Total lines in updated jittracefile = 16871
```

**Comment by eliaslopezgt** [comment]
@balag0 and @safihamid, the problem was the instructions assumed building the host in debug not release.
these are the new stats. the file has been updated in this PR.

```Total lines in latest windows jittracefile = 6919
Total lines in current jittracefile = 6829
Total lines in new jittracefile = 4680
3788 duplicates were skipped
Total lines in updated jittracefile = 6848
```

**Review by safihamid — APPROVED** [review]

**Review by balag0 — APPROVED** [review]

**Pull request merged**
