### PR TITLE
Update EasyAuth from 1.4.17 to 1.5.0 for v4

### PR DESCRIPTION
**Pull request by heppersonmicrosoft**
Contains the latest runtime code for the Authentication feature.

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [x] Otherwise: Backport tracked by issue/PR #8684
* [x] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by liliankasem** [comment]
Dependency changes here are minor, would this be okay? @fabiocav @brettsam 

```
  Changed:
    - Microsoft.IdentityModel.Abstractions.dll: 6.21.0.0/6.21.0.30701 -> 6.22.0.0/6.22.0.30727
    - Microsoft.IdentityModel.JsonWebTokens.dll: 6.21.0.0/6.21.0.30701 -> 6.22.0.0/6.22.0.30727
    - Microsoft.IdentityModel.Logging.dll: 6.21.0.0/6.21.0.30701 -> 6.22.0.0/6.22.0.30727
    - Microsoft.IdentityModel.Tokens.dll: 6.21.0.0/6.21.0.30701 -> 6.22.0.0/6.22.0.30727
    - System.IdentityModel.Tokens.Jwt.dll: 6.21.0.0/6.21.0.30701 -> 6.22.0.0/6.22.0.30727
```

**Review by liliankasem — APPROVED** [review]

**Comment by fabiocav** [comment]
@heppersonmicrosoft this change is still valid, right? Would you mind addressing the conflicts? 

The dependency changes are fine, but it will require an update to the deps file to reflect the new versions. Let mw know if you need help with that and I can assist.

**Comment by heppersonmicrosoft** [comment]
@fabiocav - thanks for bumping this back to my attention, realized I had missed the latest updates on email thread when I was oof. We actually found a small bug with this version (1.5.0), and have a newer version that may be better to use here.

**Comment by heppersonmicrosoft** [comment]
@fabiocav new PR here: https://github.com/Azure/azure-functions-host/pull/8876

**Pull request closed without merging**
