### PR TITLE
cherry-picking relevant dev commits to v4.x

### PR DESCRIPTION
**Pull request by brettsam**

### CODE REVIEW

**Comment by mathewc** [comment]
What about https://github.com/Azure/azure-functions-host/commit/405a25dc064d3cc85f5c6419361db87c610386a1? Shouldn't that be carried forward?

**Comment by brettsam** [comment]
@mathewc -- no, a different PR was made to `v4.x` (https://github.com/Azure/azure-functions-host/pull/7671) -- that's what made a merge from dev really hard and I ended up cherry-picking everything but that one (and the host version update).

**Comment by mathewc** [comment]
We need @alrod to confirm. From what I see https://github.com/Azure/azure-functions-host/commit/405a25dc064d3cc85f5c6419361db87c610386a1 is a superset of https://github.com/Azure/azure-functions-host/pull/7671 and needs to be carried forward. I guess that can happen in a separate merge PR - I'll sign off on this one. I just did a quick sanity check of the commits for this PR and noticed this discrepancy.

**Review by mathewc — APPROVED** [review]

**Comment by brettsam** [comment]
he just confirmed that i was wrong on Teams so i'm going to abandon this... i'm going to take another look at the merge and see if i can figure out why it's getting so mangled

**Pull request closed without merging**
