### PR TITLE
[WIP] Exposing AppInsights endpoint configs in V1

### PR DESCRIPTION
**Pull request by gzuber**
Resolves #2284

### CODE REVIEW

**Comment by fabiocav** [comment]
@gzuber is this still relevant?

**Comment by fabiocav** [comment]
Closing stale PRs. Please reopen if still relevant.

**Comment by paulbatum** [comment]
I'm hearing about a few government customers that are having problems in gov cloud because they're on functions V1, and app insights in that environment requires the connection string. What was blocking this PR?

**Comment by gzuber** [comment]
The main changes in this PR were merged here: https://github.com/Azure/azure-functions-host/pull/6652

**Pull request closed without merging**
