### PR TITLE
add multipart support

### PR DESCRIPTION
**Pull request by christopheranderson**
fixes https://github.com/Azure/azure-functions-host/issues/2009

### CODE REVIEW

**Comment by zedr** [comment]
> Might be worth it to fix this in V1 as well as it's a simple one.

+1 It would be great to have it in V1. I was planning in implementing an Azure function in Python that handles uploads, and this is a blocker for me.

**Comment by christopheranderson** [comment]
Unfortunately, we believe this is a breaking change for v1 and so we've decided not to backport this at this time (we could do it behind a feature flag/etc.)

You should be able to work around this by converting from UTF8 to bytes, which will give you back the raw bytes (the bug was that we were converting the blob in to UTF8.

**Comment by veris-neerajdhiman** [comment]
@christopheranderson  I facing the same issue and as you said I tried reading the content with `encoding="utf8"` Bujt I am still getiing the error 

`UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 133: character maps to <undefined>`

My code is `open(os.environ['req'], encoding="utf8").read()` . 

Please let me know where I am doing this wrong.

**Comment by zedr** [comment]
Yes, I've also tried that but I was unsuccessful. What a pity.

**Comment by veris-neerajdhiman** [comment]
@zedr any workaround you able to find out ????

**Comment by pragnagopa** [comment]
@veris-neerajdhiman / @zedr  - Can you please confirm if you are using V2? If you are using V2 and not seeing the issue fixed, please go ahead active issue #2009

**Comment by veris-neerajdhiman** [comment]
No, I am using v1 . I tried with beta version but then function start
giving 404 error.

**Comment by veris-neerajdhiman** [comment]
@christopheranderson / @pragnagopa  
- I was able to read data from request like `postreqdata =open(os.environ['req'], 'rb',).read()` and there was no encoding errors
- But Now I am not able to get `file` object from  `postreqdata` so that I can save my file send in `POST`. 

- If I am reading the post data correctly then how can I retrieve that file from post data ?

**Comment by spacem** [comment]
@christopheranderson 

you say:

> "You should be able to work around this by converting from UTF8 to bytes, which will give you back the raw bytes"

Correct my if I am wrong but an excel document I upload will have had non-utf8 characters so those bytes will have been lost and converted into unicode replacement characters�

The azure functions docs are really lacking and scattered. On this page I see that dataType can be stream, binary or string:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings

> "For languages that are dynamically typed such as JavaScript, use the dataType property in the function.json file. For example, to read the content of an HTTP request in binary format, set dataType to binary: Other options for dataType are stream and string."

Is that version2 only? Where is an example application that uses these options? In version1 I tried setting that to stream but the body still appears to be a string. (I assume we use the body since no doc tells me how to find the stream???) From what I read v2 is not production ready so using that is not really an option. I guess there is really no workaround right? Does it even work if you use some other programming language or is there just no multipart support for azure function?

Please any workaround will be helpful.

**Pull request merged**
